#if !defined(AFX_VTSLIDER_H__6B4B2EFE_B806_4D8A_B428_DE2FD2C2189E__INCLUDED_)
#define AFX_VTSLIDER_H__6B4B2EFE_B806_4D8A_B428_DE2FD2C2189E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;

/////////////////////////////////////////////////////////////////////////////
// CVTSlider wrapper class

class CVTSlider : public CWnd
{
protected:
	DECLARE_DYNCREATE(CVTSlider)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x232343f7, 0x5d35, 0x475e, { 0x8f, 0xf7, 0xf2, 0x4e, 0x91, 0x18, 0xab, 0x8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetMin();
	void SetMin(long);
	long GetMax();
	void SetMax(long);
	BOOL GetShowTick();
	void SetShowTick(BOOL);
	short GetTickFreq();
	void SetTickFreq(short);
	long GetPosLo();
	void SetPosLo(long);
	long GetPosHi();
	void SetPosHi(long);
	BOOL GetShowNums();
	void SetShowNums(BOOL);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	BOOL GetCycled();
	void SetCycled(BOOL);
	BOOL GetAutoUpdate();
	void SetAutoUpdate(BOOL);
	CString GetLowKeyValue();
	void SetLowKeyValue(LPCTSTR);
	CString GetHighKeyValue();
	void SetHighKeyValue(LPCTSTR);
	CString GetName();
	void SetName(LPCTSTR);
	BOOL GetInnerRaised();
	void SetInnerRaised(BOOL);
	BOOL GetInnerSunken();
	void SetInnerSunken(BOOL);
	BOOL GetOuterRaised();
	void SetOuterRaised(BOOL);
	BOOL GetOuterSunken();
	void SetOuterSunken(BOOL);
	BOOL GetSingleSlide();
	void SetSingleSlide(BOOL);

// Operations
public:
	void SetBothLimits(long nLow, long nHigh);
	void StoreToData();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VTSLIDER_H__6B4B2EFE_B806_4D8A_B428_DE2FD2C2189E__INCLUDED_)
