//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by shell.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_TITLE                       101
#define IDD_TETRIS_DIALOG               102
#define IDS_STR_DISTR_VER               102
#define IDS_SELECT_FOLDER_DLG_TITLE     103
#define IDS_READONLY_FORMAT             104
#define IDS_NOT_ENOUGH_FREE_DISK_SPACE  105
#define IDS_LOCATING                    106
#define IDS_CANT_OPEN                   107
#define IDS_USER_NOT_ADMIN              108
#define IDR_MAINFRAME                   128
#define IDR_SHELLTYPE                   129
#define IDR_ACTIONS                     129
#define IDD_ENTER_NAME                  129
#define IDS_CANTSTARTENGEENE            130
#define IDR_POPUP_TOOLBAR               130
#define IDR_USERIMAGES                  130
#define IDS_NOACTMAN                    131
#define IDS_NOCMNDMAN                   132
#define IDD_ACTION_SETTINGS             132
#define IDS_BAD_TOOLBAR_IDX             133
#define IDB_PATTERN                     133
#define IDS_CANT_CREATE_TOOLBAR         134
#define IDD_CHOOSE_WINDOW               134
#define IDS_FILE_OPEN_DLG_TITLE         135
#define IDS_BAD_DOCUMENT_TEMPLATE       136
#define IDS_CANT_FIND_DOCUMENT_TEMPLATE 137
#define IDS_FILE_SAVE_DLG_TITLE         138
#define IDS_FILE_SAVEAS_DLG_TITLE       139
#define IDS_FILTER_STATE                140
#define IDS_NONTFCONTR                  141
#define IDS_NONAMEDDATA                 142
#define IDS_NONAMEDDATA2                143
#define IDS_NOCONTEXT                   144
#define IDS_UNAVAIBLE_ACTION            145
#define IDS_FAILED_TO_OPEN_DOC          146
#define IDS_CUSTOMIZE                   147
#define IDS_OUTLOOK_BAR                 148
#define IDS_NO_RECENT_FILES             149
#define IDS_FILE_OPEN                   150
#define IDS_NO_WINDOWS                  151
#define IDR_TOOLBAR_APPEND              152
#define IDS_ACTIVATE_WINDOW             152
#define IDD_DUMMY                       153
#define IDR_TOOLBAR_APPEND_POPUP        153
#define IDS_GUARD_FILE_READ_FAILED      153
#define IDS_CANT_SAVE_ALL_OBJECTS       154
#define IDD_DIALOG1                     155
#define IDS_NOTSOURCEOBJECT             155
#define IDS_OLE_SERVER_WARNING          156
#define IDS_DEFAULT_GROUP_CUST          156
#define IDS_NEW_MENU                    157
#define IDS_NEW_MENU_CUST               157
#define IDS_ALLFILTER_NAME_FORMAT       158
#define IDS_PRINT_UNSUPPORTED           159
#define IDD_SPLASH                      160
#define IDS_COMPRESSOR_NOT_FOUND        160
#define IDS_METHODIC_RUNNING            161
#define IDS_METHODIC_RECORDING          162
#define IDI_STATUS_MOUSEPOS             163
#define IDI_STATUS_CLIENTSIZE           165
#define IDB_BITMAP1                     166
#define IDB_BITMAP2                     167
#define IDB_CAPIONBUTTONS               172
#define IDD_VERSION                     175
#define IDD_WAITDLG                     176
#define IDB_SLIDE                       177
#define ID_VIEW_USER_TOOLBAR1           200
#define ID_VIEW_USER_TOOLBAR2           201
#define ID_VIEW_USER_TOOLBAR3           202
#define ID_VIEW_USER_TOOLBAR4           203
#define ID_VIEW_USER_TOOLBAR5           204
#define ID_VIEW_USER_TOOLBAR6           205
#define ID_VIEW_USER_TOOLBAR7           206
#define ID_VIEW_USER_TOOLBAR8           207
#define ID_VIEW_USER_TOOLBAR9           208
#define ID_VIEW_USER_TOOLBAR10          209
#define ID_VIEW_USER_TOOLBAR11          210
#define ID_VIEW_USER_TOOLBAR12          211
#define ID_VIEW_USER_TOOLBAR13          212
#define ID_VIEW_USER_TOOLBAR14          213
#define ID_VIEW_USER_TOOLBAR15          214
#define ID_VIEW_USER_TOOLBAR16          215
#define ID_VIEW_USER_TOOLBAR17          216
#define ID_VIEW_USER_TOOLBAR18          217
#define ID_VIEW_USER_TOOLBAR19          218
#define ID_VIEW_USER_TOOLBAR20          219
#define IDC_NODRAGGING                  268
#define IDC_TETPLACE                    1000
#define IDC_SCOPE                       1001
#define IDC_WINDOWS                     1002
#define IDC_LEVEL                       1002
#define IDC_TABLE                       1003
#define IDC_NAME                        1004
#define IDC_LINES                       1004
#define IDC_NEW                         1005
#define IDC_ACIVECOLORSVIEWCTRL1        1020
#define IDC_EDIT2                       1033
#define IDC_SPIN2                       1034
#define IDC_VTEDITOR1                   1035
#define IDC_TITLE                       1039
#define IDC_TEXT1                       1040
#define IDC_TEXT2                       1041
#define IDC_TEXT4                       1042
#define IDC_TEXT3                       1043
#define IDC_INFO_DISTR                  1044
#define IDC_VTSTATICTEXT1               1045
#define IDC_VTD3DBARCTRL1               1046
#define IDC_VTD3DBARCTRL2               1047
#define IDC_VTD3DBARCTRL3               1048
#define IDC_LIST                        1049
#define IDC_SHOW_ONLY_OUR               1050
#define IDC_VERSION                     1051
#define IDC_PLEASE_WAIT                 1052
#define IDC_DRAGGING                    1320
#define IDC_HANDCUR                     3010
#define IDS_ACTION_FILE_EXIT            10000
#define IDS_ACTION_FILE_NEW             10001
#define IDS_ACTION_FILE_SAVE            10002
#define IDS_ACTION_FILE_OPEN            10003
#define IDS_ACTION_FILE_SAVEAS          10004
#define IDS_ACTION_FILE_CLOSE           10005
#define IDS_ACTION_FILE_CLOSE_ALL       10006
#define IDS_ACTION_FILE_CLOSE_ALL2      10007
#define IDS_ACTION_FILE_SENDEMAIL       10007
#define IDS_ACTION_FILE_SAVEVIEW        10008
#define IDS_ACTION_FILE_SENDVIEW        10009
#define IDS_ACTION_TOOLS_CUSTOMIZE      10020
#define IDS_ACTION_TOOLS_SAVE_STATE     10021
#define IDS_ACTION_TOOLS_LOAD_STATE     10022
#define IDS_ACTION_TOOLS_LOAD_STATE_EX  10023
#define IDS_ACTION_TOOLS_LOAD_STATE2    10023
#define IDS_ACTION_WINDOW_NEW           10030
#define IDS_ACTION_WINDOW_TILE          10031
#define IDS_ACTION_WINDOW_TILE2         10032
#define IDS_ACTION_WINDOW_ARRANGE       10033
#define IDS_ACTION_WINDOW_TILE3         10034
#define IDS_ACTION_WINDOW_ACTIVATE      10035
#define IDS_ACTION_HELP_ABOUT           10036
#define IDS_ACTION_HELP_CONTEXT         10037
#define IDS_HELP_INDEX                  10038
#define IDS_ACTION_SHOW_VERSION         10039
#define IDS_ACTION_HELP                 10040
#define IDS_ACTION_DUMP_MEM             10040
#define IDS_ACTION_TOOLS_SAVEAS_STATE   10041
#define IDS_MENU_FILE                   20000
#define IDS_MENU_TOOLS                  20001
#define IDS_MENU_WINDOW                 20002
#define IDS_MENU_FILE_DOC               20003
#define IDS_MENU_HELP                   20004
#define IDS_TB_FILE                     20500
#define IDS_TB_HELP                     20501
#define ID_VIEW_USER_TOOBAR             32774
#define ID_VIEW_CUSTOMIZE               32775
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_BUTTON32785                  32785
#define ID_TOOLBAR_MENUBUTTON           32787
#define ID_TOOLBAR_COMMANDLIST          32788
#define ID_SHOW_AS_TEXT                 32789
#define ID_SHOW_AS_IMAGE                32790
#define ID_SHOW_AS_IMAGE_AND_TEXT       32791
#define ID_ACTION_INFO                  32793
#define ID_BUTTON32886                  32886
#define IDS_READY                       61447
#define IDS_OLE_FILE                    61448
#define IDS_XP_DETAILS                  61449
#define IDS_DOC_NOT_SAVEABLE            61450
#define IDS_MENU_BAR_NAME               61451
#define IDS_ALLFILTER                   61452

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32887
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
