//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StatUI.rc
//
#define IDI_STAT_OBJECT                 102
#define IDS_STAT_VIEW_NAME              102
#define IDS_STAT_OBJECT_TYPE_NAME       103
#define IDI_STAT_OBJECT1                103
#define IDI_STAT_CMP                    103
#define IDS_STAT_OBJECT_FILTERNAME      104
#define IDS_CHART_VIEW_ONOFF            105
#define IDS_LEGEND_VIEW_ONOFF           106
#define IDS_TABLE_VIEW_ONOFF            107
#define IDS_CREATE_STAT_OBJECT          108
#define IDS_TOTAL                       109
#define IDS_CLASSNAME                   110
#define IDS_PARAM_MX                    111
#define IDS_PARAM_GEOM                  112
#define IDS_PARAM_GORM                  113
#define IDS_PARAM_MIN                   114
#define IDS_PARAM_MAX                   115
#define IDS_PARAM_VAR                   116
#define IDS_PARAM_DISP                  117
#define IDS_PARAM_STDDEV                118
#define IDS_PARAM_MODE                  119
#define IDS_PARAM_MEDIANE               120
#define IDS_PARAM_ASSIMETRY             121
#define IDS_PARAM_EXCESS                122
#define IDS_PARAM_COEFVAR               123
#define IDS_NOVAL                       124
#define IDS_CHART_BEGIN_END             125
#define IDS_CHART_STEP                  126
#define IDS_CHART_CLASSES               127
#define IDS_CHART_MODEL                 128
#define IDS_CHI_SQUARE                  129
#define IDS_FISHER                      130
#define IDS_PARAM_COUNT                 131
#define IDS_CLASSES                     132
#define IDS_NOEXPR                      133
#define IDS_ASSIGN_VIRTUAL_CLASS        134
#define IDS_SHOW_VIRTUAL_CLASS          135
#define IDS_PARAM_AREA                  136
#define IDS_PARAM_LENGTH                137
#define IDS_PARAM_USEDAREA              138
#define IDS_PARAM_SPECAREA              139
#define IDS_PARAM_AREAPERC              140
#define IDS_PARAM_SPECAREA_ERR          141
#define IDS_PARAM_AREAPERC_ERR          142
#define IDS_PARAM_NORMAL_AREA           143
#define IDS_PARAM_SPECCOUNT             144
#define IDS_PARAM_SPECCOUNT_ERR         145
#define IDS_PARAM_COUNTPERC             146
#define IDS_PARAM_COUNTPERC_ERR         147
#define IDS_PARAM_NORMAL_COUNT          148
#define IDS_PARAM_SPECLEN               149
#define IDS_PARAM_SPECLEN_ERR           150
#define IDS_PARAM_3DPART                151
#define IDS_PARAM_MXERR                 152
#define IDS_PARAM_MXPROB                153
#define IDS_PARAM_CHI_SQUARE            154
#define IDS_PARAM_CHI_SQUARE_LOG        155
#define IDS_PARAM_IMAGE_COUNT           156
#define IDS_PARAM_FULLAREA              157
#define IDS_NO_DATA                     158
#define IDS_NO_LOG                      159
#define IDS_NO_LOG_TITLE                160
#define IDS_NO_LOG_CHI_SQUARE           161
#define IDS_ERROR_TITLE                 162
#define IDS_AXIS_LABEL_ERROR_X          163
#define IDS_AXIS_LABEL_ERROR_Y          164
#define IDS_AXIS_VALUES_ERROR_X         165
#define IDS_AXIS_VALUES_ERROR_Y         166
#define IDS_AXIS_GRID_ERROR_X           167
#define IDS_AXIS_GRID_ERROR_Y           168
#define IDS_PARAM_PERIMETR              169
#define IDS_PARAM_SURF_AREA             170
#define IDS_PARAM_MDL_CHORD             171
#define IDS_PARAM_MDL_DIST              172
#define IDS_PARAM_SURFAREAPERC          173
#define IDS_PARAM_SPEC_SURF_PERC        174
#define IDS_PARAM_SPEC_SURF             175
#define IDS_CHART_TITLE_COMPARE         176
#define IDS_LEGEND_TITLE_COMPARE        177
#define IDS_PARAM_STDDEV_LOG            178
#define IDS_PARAM_MXERR_LOG             179
#define IDS_PARAM_MX_LOG                180
#define IDS_PARAM_DISP_LOG              181
#define IDS_PARAM_MXPROB_LOG            182
#define IDS_PARAM_MODE_LOG              183
#define IDS_PARAM_ASSIMETRY_LOG         184
#define IDS_PARAM_EXCESS_LOG            185
#define IDS_PARAM_COEFVAR_LOG           186
#define IDS_PARAM_MX_LOGNORM            187
#define IDS_PARAM_DISP_LOGNORM          188
#define IDS_PARAM_MODE_LOGNORM          189
#define IDS_PARAM_ASSIMETRY_LOGNORM     190
#define IDS_PARAM_EXCESS_LOGNORM        191
#define IDS_PARAM_CHI_SQUARE_LOGNORM    192
#define IDS_PARAM_CHI2_CRITIC           193
#define IDS_ALL_YVALUES_ZERO            194
#define IDS_LOGSCALE_MAX_INVALID        195
#define IDS_PARAM_WEIGHTED_AVERAGE      196
#define IDS_PARAM_CHI2_PROB             197
#define IDS_PARAM_CHI2_PROB_LOG         198
#define IDS_CMP_STAT_OBJECT_TYPE_NAME   199
#define IDS_DOCUMENT                    200
#define IDS_TABLE_NUMBER                201
#define IDS_EQUAL                       202
#define IDS_NOT_EQUAL                   203
#define IDS_DISP_EQ                     204
#define IDS_DX_EQ                       204
#define IDS_FISHERS_TEST                205
#define IDS_MX_EQ                       206
#define IDS_STUDENTS_TEST               207
#define IDS_FILES                       208
#define IDS_CMP_VIEW_NAME               209
#define IDS_SHOW_STAT_OBJECT_VIEW       501
#define IDS_SHOW_STAT_CMP_VIEW          502
#define IDR_ACTIONS                     1000
#define IDB_HOTZONE                     9005
#define IDS_CHART_CMP_ONOFF             32781
#define IDS_LEGEND_CMP_ONOFF            32782
#define IDS_TABLE_CMP_ONOFF             32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9008
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         9001
#define _APS_NEXT_SYMED_VALUE           9000
#endif
#endif
