//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Baumer.rc
//
#define IDS_BAUMER                      1
#define IDS_ERROR_COPYING_FILE          2
#define IDS_STATIC_HSS                  3
#define IDS_STATIC_LSS                  4
#define IDS_TIME_MESSAGE                5
#define IDS_8BIT                        6
#define IDS_STOP                        7
#define IDS_STATIC_SHUTTER              8
#define IDS_10BIT_AUTO                  9
#define IDS_10BIT_MANUAL                10
#define IDS_10BIT_NOCONV                11
#define IDS_12BIT_AUTO                  12
#define IDS_12BIT_MANUAL                13
#define IDS_12BIT_NOCONV                14
#define IDD_BAUMER                      2000
#define IDC_SETTINGS                    2001
#define IDD_SETTINGS                    2001
#define IDC_IMAGE                       2002
#define IDC_CX13C                       2003
#define IDC_CX13G                       2004
#define IDC_CX05C                       2005
#define IDD_HISTO                       2005
#define IDC_CX05G                       2006
#define IDC_HIGHSPEED                   2007
#define IDC_LOWSPEED                    2008
#define IDC_E_HIGHSPEED                 2009
#define IDC_E_LOWSPEED                  2010
#define IDC_S_HIGHSPEED                 2011
#define IDC_S_LOWSPEED                  2012
#define IDC_E_GAIN                      2013
#define IDC_S_GAIN                      2014
#define IDC_E_OFFSET                    2015
#define IDC_S_OFFSET                    2016
#define IDC_E_BRIGHTNESS                2017
#define IDC_S_BRIGHTNESS                2018
#define IDC_E_CONTRAST                  2019
#define IDC_S_CONTRAST                  2020
#define IDC_E_SATURATION                2021
#define IDC_S_SATURATION                2022
#define IDC_E_WB_RED                    2023
#define IDC_S_WB_RED                    2024
#define IDC_E_WB_GREEN                  2025
#define IDC_S_WB_GREEN                  2026
#define IDC_E_WB_BLUE                   2027
#define IDC_S_WB_BLUE                   2028
#define IDC_WB_DEFAULT                  2029
#define IDC_WB_ENABLE                   2030
#define IDC_CB_ENABLE                   2031
#define IDC_STATIC_HS                   2032
#define IDC_STATIC_LS                   2033
#define IDC_DEFAULT                     2034
#define IDC_OVERLAY                     2035
#define IDC_E_CB_RED                    2036
#define IDC_S_CB_RED                    2037
#define IDC_E_CB_GREEN                  2038
#define IDC_S_CB_GREEN                  2039
#define IDC_E_CB_BLUE                   2040
#define IDC_S_CB_BLUE                   2041
#define IDS_PROPSHT_CAPTION             2042
#define IDC_CAMERA                      2043
#define IDS_RESTART_CAMERA              2043
#define IDC_10Bit                       2044
#define IDC_BINING                      2045
#define IDC_AGP                         2046
#define IDC_E_LEFT_MARGIN               2047
#define IDC_S_LEFT_MARGIN               2048
#define IDC_E_RIGHT_MARGIN              2049
#define IDC_S_RIGHT_MARGIN              2050
#define IDC_E_TOP_MARGIN                2051
#define IDC_S_TOP_MARGIN                2052
#define IDC_E_BOTTOM_MARGIN             2053
#define IDC_S_BOTTOM_MARGIN             2054
#define IDC_REFRESH_TIME                2055
#define IDC_AUTO_SETUP                  2056
#define IDC_PROGRESS_AUTO               2057
#define IDD_AMPL                        2058
#define IDD_CAMERA                      2059
#define IDD_WHITE_BALANCE               2060
#define IDD_COLOR_BALANCE               2061
#define IDD_FRAME                       2062
#define IDC_S_SHUTTER                   2062
#define IDC_STATIC_SHUTTER_VAL          2063
#define IDD_MANUAL                      2063
#define IDC_E_SHUTTER                   2064
#define IDD_TRIGGER                     2064
#define IDC_STATIC_SHUTTER              2065
#define IDC_GRAFFIC                     2066
#define IDC_HISTO                       2067
#define IDC_GRAY                        2068
#define IDC_RED                         2069
#define IDC_GREEN                       2070
#define IDC_BLUE                        2071
#define IDC_PREVIEW_ALL_FRAME           2072
#define IDC_COMBO_BITS                  2074
#define IDC_GRAY_SCALE                  2075
#define IDC_STATIC_MSG                  2076
#define IDC_STATIC_COLOR_PLANE          2077
#define IDC_COMBO_COLOR_PLANE           2078
#define IDC_E_PROC_WHITE                2080
#define IDC_SP_PROC_WHITE               2081
#define IDC_S_PROC_WHITE                2082
#define IDC_SP_SHUTTER                  2083
#define IDC_SP_OFFSET                   2084
#define IDC_SP_GAIN                     2085
#define IDC_SP_RED                      2090
#define IDC_SP_GREEN                    2091
#define IDC_SP_BLUE                     2092
#define IDC_SP_CB_RED                   2093
#define IDC_SP_CB_GREEN                 2094
#define IDC_SP_CB_BLUE                  2095
#define IDC_ENABLE_FRAME                2096
#define IDC_NATURAL_SIZE                2097
#define IDC_STATIC_TOP                  2098
#define IDC_E_TOP                       2099
#define IDC_SP_TOP                      2100
#define IDC_STATIC_BOTTOM               2101
#define IDC_E_BOTTOM                    2102
#define IDC_SP_BOTTOM                   2103
#define IDC_SHUTTER_AUTO                2108
#define IDC_CAMERA_SYSTEM_MANAGER       2109
#define IDC_STATIC_MAX_POINTS           2110
#define IDC_STATIC_MAX_COLOR            2111
#define IDC_STATIC_0                    2112
#define IDC_EDIT_GAMMA                  2114
#define IDC_SPIN_GAMMA                  2115
#define IDC_SLIDER_GAMMA                2116
#define IDC_STATIC_GAMMA                2117
#define IDC_TRIGGER_MODE                2118
#define IDC_DISCHARGE                   2119
#define IDC_SOFTWARE_TRIGGER            2120
#define IDS_INPUT                       61926
#define IDS_TIME_MICROSECS              61927
#define IDS_TIME_MILLISECS              61928
#define IDS_TIME_SECS                   61929

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2010
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2121
#define _APS_NEXT_SYMED_VALUE           2063
#endif
#endif
