// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "acivecolorsview.h"

/////////////////////////////////////////////////////////////////////////////
// CAciveColorsView

IMPLEMENT_DYNCREATE(CAciveColorsView, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CAciveColorsView properties

CString CAciveColorsView::GetBMPFileName()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CAciveColorsView::SetBMPFileName(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

unsigned long CAciveColorsView::GetLeftBtnTransparentColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CAciveColorsView::SetLeftBtnTransparentColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

unsigned long CAciveColorsView::GetRightBtnTransparentColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CAciveColorsView::SetRightBtnTransparentColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

unsigned long CAciveColorsView::GetLeftBtnColor()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CAciveColorsView::SetLeftBtnColor(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

unsigned long CAciveColorsView::GetRightBtnColor()
{
	unsigned long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CAciveColorsView::SetRightBtnColor(unsigned long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

unsigned long CAciveColorsView::GetColorTransparent()
{
	unsigned long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CAciveColorsView::SetColorTransparent(unsigned long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CAciveColorsView operations

void CAciveColorsView::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
