#if !defined(AFX_ACIVECOLORSVIEW_H__BE0B02A5_A0AE_11D3_A538_0000B493A187__INCLUDED_)
#define AFX_ACIVECOLORSVIEW_H__BE0B02A5_A0AE_11D3_A538_0000B493A187__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAciveColorsView wrapper class

class CAciveColorsView : public CWnd
{
protected:
	DECLARE_DYNCREATE(CAciveColorsView)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc1f6a8b, 0x9db3, 0x11d3, { 0xa5, 0x36, 0x0, 0x0, 0xb4, 0x93, 0xa1, 0x87 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetBMPFileName();
	void SetBMPFileName(LPCTSTR);
	unsigned long GetLeftBtnTransparentColor();
	void SetLeftBtnTransparentColor(unsigned long);
	unsigned long GetRightBtnTransparentColor();
	void SetRightBtnTransparentColor(unsigned long);
	unsigned long GetLeftBtnColor();
	void SetLeftBtnColor(unsigned long);
	unsigned long GetRightBtnColor();
	void SetRightBtnColor(unsigned long);
	unsigned long GetColorTransparent();
	void SetColorTransparent(unsigned long);

// Operations
public:
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ACIVECOLORSVIEW_H__BE0B02A5_A0AE_11D3_A538_0000B493A187__INCLUDED_)
