// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "palette.h"

/////////////////////////////////////////////////////////////////////////////
// CPaletteCtrl

IMPLEMENT_DYNCREATE(CPaletteCtrl, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPaletteCtrl properties

short CPaletteCtrl::GetCols()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CPaletteCtrl::SetCols(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

short CPaletteCtrl::GetRows()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CPaletteCtrl::SetRows(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

short CPaletteCtrl::GetCellWidth()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CPaletteCtrl::SetCellWidth(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

short CPaletteCtrl::GetCellHeight()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CPaletteCtrl::SetCellHeight(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

short CPaletteCtrl::GetIntercellSpace()
{
	short result;
	GetProperty(0x5, VT_I2, (void*)&result);
	return result;
}

void CPaletteCtrl::SetIntercellSpace(short propVal)
{
	SetProperty(0x5, VT_I2, propVal);
}

BOOL CPaletteCtrl::GetInnerSunken()
{
	BOOL result;
	GetProperty(0x6, VT_BOOL, (void*)&result);
	return result;
}

void CPaletteCtrl::SetInnerSunken(BOOL propVal)
{
	SetProperty(0x6, VT_BOOL, propVal);
}

BOOL CPaletteCtrl::GetOuterRaised()
{
	BOOL result;
	GetProperty(0x7, VT_BOOL, (void*)&result);
	return result;
}

void CPaletteCtrl::SetOuterRaised(BOOL propVal)
{
	SetProperty(0x7, VT_BOOL, propVal);
}

BOOL CPaletteCtrl::GetOuterSunken()
{
	BOOL result;
	GetProperty(0x8, VT_BOOL, (void*)&result);
	return result;
}

void CPaletteCtrl::SetOuterSunken(BOOL propVal)
{
	SetProperty(0x8, VT_BOOL, propVal);
}

short CPaletteCtrl::GetBorderSize()
{
	short result;
	GetProperty(0x9, VT_I2, (void*)&result);
	return result;
}

void CPaletteCtrl::SetBorderSize(short propVal)
{
	SetProperty(0x9, VT_I2, propVal);
}

BOOL CPaletteCtrl::GetInnerRaised()
{
	BOOL result;
	GetProperty(0xa, VT_BOOL, (void*)&result);
	return result;
}

void CPaletteCtrl::SetInnerRaised(BOOL propVal)
{
	SetProperty(0xa, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CPaletteCtrl operations

void CPaletteCtrl::SetDefaultColors()
{
	InvokeHelper(0xb, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CPaletteCtrl::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
