#if !defined(AFX_PALETTE_H__BE0B02A4_A0AE_11D3_A538_0000B493A187__INCLUDED_)
#define AFX_PALETTE_H__BE0B02A4_A0AE_11D3_A538_0000B493A187__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CPaletteCtrl wrapper class

class CPaletteCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CPaletteCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x57c4cb48, 0x9e87, 0x11d3, { 0xa5, 0x37, 0x0, 0x0, 0xb4, 0x93, 0xa1, 0x87 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	short GetCols();
	void SetCols(short);
	short GetRows();
	void SetRows(short);
	short GetCellWidth();
	void SetCellWidth(short);
	short GetCellHeight();
	void SetCellHeight(short);
	short GetIntercellSpace();
	void SetIntercellSpace(short);
	BOOL GetInnerSunken();
	void SetInnerSunken(BOOL);
	BOOL GetOuterRaised();
	void SetOuterRaised(BOOL);
	BOOL GetOuterSunken();
	void SetOuterSunken(BOOL);
	short GetBorderSize();
	void SetBorderSize(short);
	BOOL GetInnerRaised();
	void SetInnerRaised(BOOL);

// Operations
public:
	void SetDefaultColors();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PALETTE_H__BE0B02A4_A0AE_11D3_A538_0000B493A187__INCLUDED_)
