//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DBaseDoc.rc
//
#define IDS_TEMPLATE                    1
#define IDB_DBTEXT                      1
#define IDD_ABOUTBOX_DBTEXT             1
#define IDS_STRING2                     2
#define IDB_DBNUMBER                    2
#define IDS_DBTEXT                      2
#define IDD_ABOUTBOX_DBNUMBER           2
#define IDS_RECORD_PANE_FORMAT          2
#define IDB_DBDATETIME                  3
#define IDS_DBTEXT_PPG                  3
#define IDD_ABOUTBOX_DBDATETIME         3
#define IDOK2                           3
#define IDS_WARNING_DELETE_RECORD       3
#define IDS_DBNUMBER                    4
#define IDCANCEL2                       4
#define IDS_QUERY_TYPE                  4
#define IDS_DBNUMBER_PPG                5
#define IDS_BLABK_TYPE                  5
#define IDS_DBDATETIME                  6
#define IDS_CONVERTION_DONE             6
#define IDS_DBDATETIME_PPG              7
#define IDS_ERROR_CONVERT               7
#define IDS_DBCOMMON_PPG                8
#define IDS_RECORD_FORMAT               8
#define IDS_BLANKVIEW_NAME              9
#define IDS_GRID_NAME                   10
#define IDS_GALLERY_NAME                11
#define IDS_BLANK_MENU                  12
#define IDS_GALLERY_MENU                13
#define IDS_GRID_MENU                   14
#define IDS_EXPORT_FILE_EQUAL           15
#define IDS_DBASE_FILE_FILTER           16
#define IDS_FILE_EXIST                  17
#define IDS_DELETE_WARNING              18
#define IDS_STRING19                    19
#define IDS_UPDATE_RECORDSET_INFO       19
#define IDS_MANY_USERS                  20
#define IDS_USER                        21
#define IDS_STRING22                    22
#define IDS_MACHINE                     22
#define IDS_EMPTY_VALUE                 23
#define IDS_COMPACT_ERROR               24
#define IDS_COMPUTER                    25
#define IDS_EXCLUSIVE_REQUEST_RECEIVED  26
#define IDS_ER_ERROR                    27
#define IDS_ATTENTION                   28
#define IDS_DBSIZE_WARNING              29
#define IDS_DBASE_BACKUP_TO_OPTIC       30
#define IDS_INSERTDISC                  31
#define IDS_MEDIA_UNSUPPORTED2          32
#define IDS_MEDIA_UNSUPPORTED           32
#define IDS_READY_TOBURN2               33
#define IDS_READY_TOBURN                33
#define IDS_NA                          34
#define IDS_MEDIADAMAGED                35
#define IDS_MEDIAPROTECTED              36
#define IDS_NOTBLANK_NOTAPPENDABLE      37
#define IDS_NOTENOUGHSPACE              38
#define IDS_DIRECTORY_WAS_MOVED_OR_REMOVED 39
#define IDS_BURN_SUCCEED                40
#define IDS_BURN_FAIL                   41
#define IDS_NO_RECORDER                 42
#define IDS_NO_MEDIA                    43
#define IDS_MEDIA_BUSY                  44
#define IDS_WRITEPROTECTED              45
#define IDS_NORESPONSE                  46
#define IDS_UPSIDE_DOWN                 47
#define IDS_INITIALIZING                48
#define IDS_UNKNOWNERROR                49
#define IDC_AREA                        100
#define IDC_TEST1                       101
#define IDC_TEST2                       102
#define IDD_FIELD_OBJ_PAGE              107
#define IDD_GRID_OPTIONS_DIALOG         130
#define IDB_CHECK                       132
#define IDC_CURSOR_WIDTH                132
#define IDC_CURSOR_COLUMN               133
#define IDD_ERRORS                      134
#define IDC_CURSOR_HEIGHT               134
#define IDC_CURSOR_ROW                  135
#define IDC_CURSOR_COLUMN_SPLIT         136
#define IDC_CURSOR_ROW_SPLIT            137
#define IDD_PROPPAGE_DBTEXT             200
#define IDS_DBTEXT_PPG_CAPTION          200
#define IDD_PROPPAGE_DBNUMBER           201
#define IDS_DBNUMBER_PPG_CAPTION        201
#define IDC_RADIO_LEFT                  201
#define IDD_PROPPAGE_DBDATETIME         202
#define IDS_DBDATETIME_PPG_CAPTION      202
#define IDS_DBCOMMON_PPG_CAPTION        203
#define IDC_VIEW_TYPE                   203
#define IDC_AUTO_ASIGN                  207
#define IDS_NOSPECIFIED_ERROR           1000
#define IDS_NOSPECIFIED_SOURCE          1001
#define IDC_ADD_ALL                     1001
#define IDS_WARNING_NO_TABLES           1002
#define IDC_REMOVE_ALL                  1002
#define IDC_DB_PATH                     1002
#define IDS_WARNING_NO_BASE_TABLE       1003
#define IDC_ADD                         1003
#define IDS_WARNING_QUERY_NAME_EXIST    1004
#define IDC_REMOVE                      1004
#define IDC_TABLES                      1005
#define IDS_PROMPT_SAVE_QUERY           1005
#define IDC_STATIC_SOURCE_GRID          1005
#define IDC_SAVE_QUERY                  1006
#define IDC_EDIT_DESCRIPTION            1006
#define IDC_ADD_QUERY                   1006
#define IDS_WARNING_NO_MDB_FILES        1006
#define IDC_STATIC_TARGET_GRID          1006
#define IDC_DELETE_QUERY                1007
#define IDC_LIST_SOURCE                 1007
#define IDC_DROP_QUERY                  1007
#define IDS_WARNING_FILE_NOT_FOUND      1007
#define IDC_QUERY                       1008
#define IDC_EDIT_GUID                   1008
#define IDS_WARNING_BAD_TABLE_NAME      1008
#define IDS_WARNING_BAD_FIELD_NAME      1009
#define IDC_EXPRESSION                  1010
#define IDS_WARNING_BAD_FIELD_TYPE      1010
#define IDC_EXPR_MASTER                 1011
#define IDS_WARNING_TABLE_NEED_PRIMARY_KEY 1011
#define IDC_EXPR_SLAVE                  1012
#define IDS_WARNING_CANT_WRITE_MDB_FILE 1012
#define IDC_PLUS                        1013
#define IDS_WARNING_NO_RECORD_FOUND     1013
#define IDC_MINUS                       1014
#define IDS_WARNING_FILE_EXIST          1014
#define IDC_DEVIDE                      1015
#define IDS_WARNING_CANTCREATE_FILE     1015
#define IDC_MULTI                       1016
#define IDS_WARNING_NOT_UNIQUE_VALUE    1016
#define IDC_LESS                        1017
#define IDS_WARNING_NO_TABLES_IN_TEMPLATE 1017
#define IDC_MORE                        1018
#define IDS_WARNING_EXECUTE_SUCCESS     1018
#define IDC_EQUAL                       1019
#define IDS_RECORDSET_EMPTY             1019
#define IDC_NOTEQUAL                    1020
#define IDS_RECORDSET_NOT_OPEN          1020
#define IDC_AND                         1021
#define IDS_WARNING_CONNECTION_OBJECT_FAILED 1021
#define IDC_LEFT_BRACKET                1022
#define IDS_WARNING_UPDATE              1022
#define IDC_RIGHT_BRACKET               1023
#define IDS_WARNING_INSERT_RECORD       1023
#define IDC_MAIN_TABLE                  1024
#define IDS_WARNING_NO_RECORD           1024
#define IDC_OR                          1025
#define IDS_WARNING_RS_CLOSE            1025
#define IDC_NOT                         1026
#define IDS_WARNING_CANT_START_ALBOM    1026
#define IDC_LIKE                        1027
#define IDS_WARNING_ALBOM_CANT_FIND_DOC 1027
#define IDS_WARNING_ALBOM_CANT_FIND_QUERY 1028
#define IDS_WARNING_CATALOG_OBJECT_FAILED 1029
#define IDS_INVALID_NUMBER              1030
#define IDS_NO_FIELD                    1031
#define IDB_PATTERN_VIEW                3003
#define IDS_QUERY_FILTERNAME            10000
#define IDS_SORT_NONE                   10001
#define IDS_SORT_ASCENDING              10002
#define IDS_SORT_DESCENDING             10003
#define IDS_MSACCESS_FILTERNAME         10004
#define IDS_ORGANIZER_VALUEOF           10005
#define IDS_ORGANIZER_SELECT_FROM       10006
#define IDS_NEW_DATABASE                10007
#define IDS_LOAD_DATABASE               10007
#define IDS_QUERY_WIZARD                10008
#define IDS_TABLE_WIZARD                10009
#define IDS_CHOICE_QUERY                10010
#define IDS_CANCEL                      10011
#define IDS_UPDATE                      10012
#define IDS_EDIT                        10013
#define IDS_INSERT_RECORD               10014
#define IDS_DELETE_RECORD               10015
#define IDS_MOVE_PREV                   10016
#define IDS_MOVE_NEXT                   10017
#define IDS_MOVE_LAST                   10018
#define IDS_MOVE_FIRST                  10019
#define IDS_SHOW_BLANK_DESIGN           10020
#define IDS_SHOW_BLANK_PREVIEW          10021
#define IDS_SHOW_GALLERY                10022
#define IDS_FILTER_MODE                 10023
#define IDS_GENERATE_REPORT_BY_BLANK    10023
#define IDS_DBASE_RESTORE               10024
#define IDS_DBASE_BACKUP                10025
#define IDS_DBASE_FINDTEXT              10026
#define IDS_DBASE_FINDTEXT_NEXT         10027
#define IDS_MENU_ADD_FILTER             10028
#define IDS_MENU_EDIT_FILTER            10029
#define IDS_MENU_DELETE_FILTER          10030
#define IDS_SHOW_DBGRID                 10031
#define IDS_DBGRID_OPTIONS              10032
#define IDS_REQUERY                     10033
#define IDS_GALLERY_OPTIONS             10034
#define IDS_DBASE_INFO                  10035
#define IDS_ANALIZE_AFTER_DDL           10036
#define IDS_GENERATE_TEMPLATES_BY_QUERY 10037
#define IDS_GENERATE_REPORT_BY_AXFORM   10038
#define IDS_EXECUTE_SQL                 10039
#define IDS_ACTION_DB_GENERATE          10040
#define IDS_DBASE_SELECT_FILTER         10041
#define IDS_QUERY_OPEN                  10041
#define IDS_CHOOSE_FILTER               10042
#define IDS_ORGANIZER_RECORDS           10043
#define IDS_ORGANIZER_WHERE             10044
#define IDS_ORGANIZER_AND               10045
#define IDS_ORGANIZER_OR                10046
#define IDS_CREATE_FILTER               10047
#define IDS_APPLY_FILTER                10048
#define IDS_SAVE_FILTER                 10049
#define IDS_FILTER_ORGANIZER            10050
#define IDS_FILTER_PROPERTY_PAGE        10051
#define IDS_FILTER_CUSTOM               10052
#define IDS_FILTER_NONE                 10053
#define IDS_FILTER_INVALID_NAME         10054
#define IDS_WARNING_FILTER_SAVE         10055
#define IDS_FILTER_RESERVED_WORD_CAN_USE 10056
#define IDS_RESERVED_WORD_ARRAY         10057
#define IDS_FILTER_SHOW_ALL             10058
#define IDS_DBASE_IMPORT                10059
#define IDS_QUERY_CLOSE                 10060
#define IDS_WARNING_OBJECT_EXIST        10061
#define IDS_ADVANSED_CONNECTION         10062
#define IDS_TITLE_DROP_TABLE            10063
#define IDS_TITLE_CHOICE_TABLE          10064
#define IDS_CAPTION_COL_FIELD           10065
#define IDS_CAPTION_COL_USER            10066
#define IDS_CAPTION_COL_FIELD_TYPE      10067
#define IDS_CAPTION_COL_IS_REQ          10068
#define IDS_CAPTION_COL_IS_DEF          10069
#define IDS_CAPTION_COL_DEF_VALUE       10070
#define IDS_CAPTION_COL_FIELD_FORMAT    10071
#define IDS_CAPTION_COL_REF_TABLE       10072
#define IDS_CAPTION_COL_REF_TABLE_FIELD 10073
#define IDS_YES                         10074
#define IDS_NO                          10075
#define IDS_TYPE_DIGIT                  10076
#define IDS_TYPE_STRING                 10077
#define IDS_TYPE_DATE_TIME              10078
#define IDS_TYPE_PRIMARY_KEY            10079
#define IDS_TYPE_FOREIGN_KEY            10080
#define IDS_TYPE_NOT_SUPPORTED          10081
#define IDS_DIFFERENT_OBJECT_TYPE       10082
#define IDS_WARNING_CANT_VISUAL_EDIT    10083
#define IDS_OPEN_CONNECTION_SUCCEDED    10084
#define IDS_WARNING_CREATE_DOC_ANYWHERE 10085
#define IDS_NEW_QUERY_PREFIX            10086
#define IDS_DEF_TABLE_NAME              10087
#define IDS_TABLE_NAME_NOT_VALID        10088
#define IDS_FIELD_NAME_NOT_VALID        10089
#define IDS_TABLE_EXIST                 10090
#define IDS_FIELD_EXIST                 10091
#define IDS_WARNING_CANT_CONTINUE       10092
#define IDS_WARNING_SET_ACCES_FILE      10093
#define IDS_WARNING_CHOOSE_SOURCE       10094
#define IDS_WARNING_QUERY_NAME_EMPTY    10095
#define IDS_WARNING_TABLE_EMPTY         10096
#define IDS_WARNING_SQL_EMPTY           10097
#define IDS_WARNING_ZERO_FIELD_COUNT    10098
#define IDS_WARNING_NO_FIELDS           10099
#define IDS_WARNING_FIELD_EXIST         10100
#define IDS_NEWDB_CREATE_ACCESDB        10101
#define IDS_NEWDB_CREATE_ADV_CON        10102
#define IDS_NEWDB_CREATE_TABLE          10103
#define IDS_NEWDB_QUERY_SIMPLE          10104
#define IDS_NEWDB_QUERY_ADV             10105
#define IDS_NEW_ACCESS_FILENAME         10106
#define IDS_NEWDB_FIELDS                10107
#define IDS_SUCCEDED                    10108
#define IDS_FAILED                      10109
#define IDS_WAS_ABORT                   10110
#define IDS_WARNING_CANTDELETE_FILE     10111
#define IDS_NEWDB_OPEN_CONNECTION       10112
#define IDS_CAPTION_QUERY_PROP          10113
#define IDS_FIELD_PROP_ON_PAGE          10114
#define IDS_ADD_SORT_FIELD_ASC          10115
#define IDS_ADD_SORT_FIELD_DESC         10116
#define IDS_REMOVE_ALL_SORT_FIELDS      10117
#define IDS_ACTION_RECORD_INFO          10118
#define IDS_FIELD_NAME                  10119
#define IDS_FIELD_LEN                   10120
#define IDS_TABLE_NAME                  10121
#define IDS_NO_FIND_RESULT              10122
#define IDS_NEW_FIELD_DIGIT             10123
#define IDS_NEW_FIELD_STRING            10124
#define IDS_NEW_FIELD_DATE_TIME         10125
#define IDS_NEW_FIELD_BINARY            10126
#define IDS_NEW_FIELD_IMAGE             10127
#define IDR_DATABASE                    21000
#define IDC_RADIO1                      21000
#define IDC_TEMPLATE                    21000
#define IDC_DEFINE_FIELD_TYPE           21000
#define IDC_TARGET                      21000
#define IDC_RADIO2                      21001
#define IDC_RADIO3                      21002
#define IDD_TABLE_DLG                   21002
#define IDD_DATABASE_DLG                21003
#define IDC_EDIT1                       21003
#define IDC_TEMPLATE_LOCATION_PATH      21003
#define IDC_BORDER_SIZE                 21003
#define IDC_RADIO4                      21003
#define IDC_EDIT_SQL                    21003
#define IDC_TABLE                       21003
#define IDC_CAPTION                     21003
#define IDC_VT4_PATH                    21003
#define IDC_VOLUMENAME                  21003
#define IDC_BUTTON1                     21004
#define IDC_DROP_TABLE                  21004
#define IDD_QUERY_DLG                   21004
#define IDC_GENERATE_HEIGHT             21004
#define IDC_LOAD_DB_LOCATION            21004
#define IDC_BTN_WORK                    21004
#define IDC_NEW_FILTER                  21004
#define IDC_EDIT2                       21004
#define IDC_VT4_BROWSE                  21004
#define IDC_USER_INFO                   21004
#define IDC_ADDSOURCE                   21004
#define IDC_CHECK1                      21005
#define IDC_ADD_TABLE                   21005
#define IDC_PICK2                       21005
#define IDC_VIEW_HEIGHT                 21005
#define IDC_LOAD_TEMPLATE_LOCATION      21005
#define IDC_BUTTON2                     21005
#define IDC_NEED_REQ                    21005
#define IDC_ASK_FOR_LOGIN               21005
#define IDC_FROM_CUR_RECORD             21005
#define IDC_SHOW_ADV                    21005
#define IDC_HAS_DEF_VALUE               21005
#define IDC_NEW_RECORD                  21005
#define IDC_VT5_BROWSE                  21005
#define IDC_OPEN                        21005
#define IDC_CLOSE                       21005
#define IDC_CHECK2                      21006
#define IDC_BUTTON3                     21006
#define IDC_RENAME_FILTER               21006
#define IDC_NEED_DEF                    21006
#define IDC_CREATE_NEW_TABLE            21006
#define IDC_OK                          21006
#define IDC_VT5_PATH                    21006
#define IDC_REMOVESOURCE                21006
#define IDC_BUTTON6                     21007
#define IDC_SELECT_AND_EXIT             21007
#define IDC_ANALIZE                     21007
#define IDC_QUERY_NAME                  21010
#define IDB_BITMAP1                     21010
#define IDD_SQL_EDIT_DLG                21011
#define IDD_FILTER_BUILDER              21013
#define IDC_GRID                        21014
#define IDD_PROPPAGE_COMMON             21014
#define IDC_ADVANCED_CONNECT            21015
#define IDC_STATUS                      21016
#define IDI_ICON_SELECTION              21016
#define IDC_EDIT_STRUCTURE              21017
#define IDI_ICON_CANTEDIT               21017
#define IDC_APPLY                       21018
#define IDC_EDIT_TABLE_NAME             21019
#define IDC_CANCEL                      21020
#define IDC_SHOW_SQL                    21021
#define IDC_USE_NATIVE_SQL              21022
#define IDB_ADD                         21022
#define IDC_TEST                        21023
#define IDB_DELETE                      21023
#define IDC_NEW_QUERY_NAME              21024
#define IDB_EDIT                        21024
#define IDC_SQL                         21025
#define IDD_TUMBNAIL                    21025
#define IDB_SORT_ACENDING               21025
#define IDD_FIND                        21026
#define IDB_SORT_DESCENDING             21026
#define IDC_CONDITION                   21028
#define IDC_FROM                        21029
#define IDD_CHOICE_QUERY                21029
#define IDC_TO                          21030
#define IDD_DBASE_INFO                  21030
#define IDC_FIELD_NAME                  21031
#define IDD_EXECUTE_SQL                 21031
#define IDC_TO_STATIC                   21032
#define IDD_GENERATE                    21032
#define IDC_PICK1                       21033
#define IDC_FILTER                      21034
#define IDD_FILTER_ORGANIZER            21034
#define IDC_ADD_FILTER                  21035
#define IDD_FILTER_CONDITION            21035
#define IDC_EDIT_FILTER                 21036
#define IDC_DELETE_FILTER               21037
#define IDD_PAGE_FILTERS                21037
#define IDC_IS_REQUIRED_VALUE           21038
#define IDI_QUERY_ICON                  21038
#define IDD_FILTER_NAME                 21039
#define IDC_IS_DEFAULT_VALUE            21040
#define IDD_DIALOG1                     21040
#define IDC_VT_OBJECT_TYPE              21041
#define IDD_DBSTUCT                     21041
#define IDC_DEFAULT_VALUE               21042
#define IDD_CHOICE_TABLE                21042
#define IDC_EDIT_QUERY                  21043
#define IDD_ADD_TABLE                   21043
#define IDC_AND_UNION                   21044
#define IDD_STRUCT_CONFIRM              21044
#define IDC_TABLE_NAME                  21045
#define IDI_DBASE                       21045
#define IDC_FIELDNAME                   21046
#define IDD_NEW_TABLE_WIZARD_NAME       21046
#define IDC_AUTOLABEL                   21047
#define IDD_NEW_TABLE_WIZARD_DEF1       21047
#define IDC_ENABLEENUMERATION           21048
#define IDD_NEW_TABLE_WIZARD_DEFINE_TYPE 21048
#define IDD_NEW_TABLE_WIZARD_DEF2       21049
#define IDD_NEW_QUERY_WIZARD_NAME       21050
#define IDC_COMBO_PICKER                21051
#define IDD_NEW_QUERY_WIZARD_SQL        21051
#define IDC_STATIC_CONDITION            21052
#define IDD_NEW_FIELD                   21052
#define IDC_STATIC_MEDIA                21052
#define IDC_VALUE_STATIC                21053
#define IDD_PROP_PAGE_EMU               21053
#define IDC_STATIC_MEDIA2               21053
#define IDD_FIELD_CHOOSER               21054
#define IDD_DELETE_FIELD                21055
#define IDC_USE_FILTER_ROW              21056
#define IDI_DBASE_OBJECT_CHILD          21056
#define IDC_USE_SORT_ROW                21057
#define IDI_DBASE_OBJECT_PARENT         21057
#define IDD_NEW_DBASE_WIZARD            21057
#define IDC_STATIC_LABEL_STATUS         21058
#define IDI_ACTIVE_QUERY                21058
#define IDD_NEW_DBASE_WIZARD_ACCESS     21058
#define IDC_STATIC_TABLE_GROUP          21059
#define IDC_BUTTON_OK                   21060
#define IDD_NEW_DBASE_WIZARD_ADV        21060
#define IDC_BUTTON_CANCEL               21061
#define IDD_NEW_DBASE_INFO              21061
#define IDC_TUMBNAIL_FIELD              21062
#define IDD_NEW_DBASE_PROCESS           21062
#define IDC_TUMBNAIL_CAPTION            21063
#define IDC_GENERATE_WIDTH              21064
#define IDD_CTRL_BAR                    21064
#define IDC_VIEW_WIDTH                  21065
#define IDI_OK                          21065
#define IDC_SPIN1                       21066
#define IDI_CANCEL                      21066
#define IDC_SPIN2                       21067
#define IDD_RECORD_INFO                 21067
#define IDC_SPIN3                       21068
#define IDC_FIND_IN_FIELD               21068
#define IDD_PLACE_TARGET                21068
#define IDC_SPIN4                       21069
#define IDC_MATCH_CASE                  21069
#define IDD_FIELD_PROPERTIES            21069
#define IDC_REGULAR_EXPRESSION          21070
#define IDC_SPIN5                       21070
#define IDD_NEW_TABLE_WIZARD_DEF3       21070
#define IDC_FIND_TEXT                   21071
#define IDC_SPIN6                       21071
#define IDD_CONVERT_VT4                 21071
#define IDC_EMPTY_DATABASE              21072
#define IDC_QUERY_LIST                  21073
#define IDD_NEW_DBASE_TEMPLATE          21073
#define IDC_PATH                        21074
#define IDD_USER_INFO                   21074
#define IDC_FILE_SIZE                   21075
#define IDD_DDL_ERROR                   21075
#define IDC_QUERY_STATE                 21076
#define IDI_ERROR_DDL                   21076
#define IDC_QUERY_RECORD_COUNT          21077
#define IDI_ICON1                       21077
#define IDC_QUERY_CURRENT_RECORD        21078
#define IDD_SIZEATLIMIT_DLG             21078
#define IDC_RESULT                      21079
#define IDD_EXCLUSIVE_DLG               21079
#define IDC_BTN_CANCEL                  21080
#define IDD_FILETOOBIG                  21080
#define IDC_GROUP_PROPERTIES            21081
#define IDC_GROUP_DEFAULT               21082
#define IDB_BREAK                       21082
#define IDC_GROUP_VT_OBJECT             21083
#define IDD_BACKUP_DLG                  21083
#define IDC_LABEL_VALUE                 21084
#define IDI_BURN                        21084
#define IDD_BACKUP_DLG1                 21084
#define IDC_LABEL_TYPE                  21085
#define IDC_FIELDS                      21086
#define IDC_EVENT                       21087
#define IDC_UINAME                      21088
#define IDC_VTD3DBARCTRL1               21090
#define IDC_COMBO1                      21092
#define IDC_FIELD                       21092
#define IDC_FIELD_TYPE                  21092
#define IDC_DRIVE_SELECTOR              21092
#define IDC_LIST2                       21093
#define IDC_COMBO2                      21093
#define IDC_BUTTON4                     21094
#define IDC_COMBO3                      21094
#define IDC_VALUE                       21094
#define IDC_CHOICE_TABLE                21094
#define IDC_BUTTON5                     21095
#define IDC_VALUE_TO                    21095
#define IDC_DELETE_TABLE                21095
#define IDC_BUTTON7                     21096
#define IDC_BUTTON8                     21097
#define IDC_LIST1                       21098
#define IDC_FILTER_LIST                 21098
#define IDC_TABLE__LIST                 21098
#define IDC_FIELD_LIST                  21098
#define IDC_LIST                        21098
#define IDC_USERSLIST                   21098
#define IDC_BUTTON9                     21099
#define IDC_BUTTON10                    21100
#define IDC_START                       21100
#define IDC_RESET_BRACKETS              21101
#define IDC_NEW                         21102
#define IDC_EDIT                        21103
#define IDC_COPY                        21104
#define IDC_FILTER_NAME                 21105
#define IDC_PREVIEW                     21106
#define IDC_STATIC_VALUE                21107
#define IDC_STATIC_VALUE_TO             21108
#define IDC_CONDITION_LIST              21108
#define IDC_NEW_COND                    21109
#define IDC_EDIT_COND                   21110
#define IDC_COPY_COND                   21111
#define IDC_REMOVE_COND                 21112
#define IDC_TREE1                       21113
#define IDC_CURENT_TABLE                21114
#define IDC_SIMPLE_QUERY                21116
#define IDC_INSERT_FIELD                21117
#define IDC_USE_TEMPLATE                21118
#define IDC_DEF_VALUE                   21119
#define IDC_DBASE_TYPE                  21120
#define IDC_USER_NAME                   21122
#define IDC_PASSWORD                    21123
#define IDC_CONNECTION_STR              21124
#define IDC_CONNECT                     21125
#define IDC_GRID_PLACE                  21127
#define IDC_IMAGE                       21128
#define IDC_STRING                      21129
#define IDC_NUMBER                      21130
#define IDC_TASK_LIST                   21130
#define IDC_DATE_TIME                   21131
#define IDC_PROCESS_LIST                21131
#define IDC_MEAN                        21132
#define IDC_OLE                         21132
#define IDC_DECSR                       21133
#define IDC_CODE                        21135
#define IDC_CODE_SRC                    21136
#define IDC_FULL_SIZE                   21136
#define IDC_STATIC_NAME                 21137
#define IDC_STATIC_TABLE                21138
#define IDC_STATIC_FIELDS_LINE          21139
#define IDC_DELETE_ROW                  21140
#define IDC_PROGRESS1                   21141
#define IDC_PROGRESS                    21141
#define IDC_BURNPROGRESS                21141
#define IDC_NEW_PATH                    21142
#define IDC_BROWSE                      21143
#define IDC_COMBOBOXEX1                 21144
#define IDC_ICONLABEL                   21145
#define IDC_GROUP                       21146
#define ID_HELPBTN                      21147
#define IDC_STATIC_DRIVE                21148
#define IDC_STATIC_MULTI                21150
#define IDC_STATIC_CLOSE                21151
#define IDC_STATIC_MULTI2               21153
#define IDC_STATIC_CLOSE2               21155
#define IDC_STATIC_DRIVE2               21156
#define IDC_STATIC_ERROR                21158
#define IDC_STATIC_ERROR_ICON           21159
#define ID_BURN                         21160
#define ID_BUTTON32793                  32793
#define IDS_FIELD_PROPERTY              32803
#define IDS_UNPACK_SUCCEDED             32804
#define IDS_PACK_SUCCEDED               32805
#define IDS_WARNING_UPDATE_FAILED       32806
#define IDS_FIELD_PROPERTIES            32807
#define IDS_OPEN_STATUS                 33000
#define IDS_CLOSE_STATUS                33001
#define IDS_CONVERT_VT4                 35000
#define IDS_DB_FROM_TEMPLATE            35001
#define IDS_DELETE_RECORDS              35002
#define IDS_EMPTY_DBFIELD               35003
#define IDS_COMPACTDB                   35004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        21085
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         21161
#define _APS_NEXT_SYMED_VALUE           21000
#endif
#endif
