[		 
	uuid(3403DE23-AF0C-4339-9CF9-22E95773F1C9),
	version(1.0),
	helpstring("VT5 StatData Type Library")
	
]
library StatDataLib
{	

	importlib("stdole2.tlb");
	[		
		object,
		uuid(340FA4B3-6D3F-470d-A489-689D0B4E8094),
		dual,		
		pointer_default(unique),		
	]	
	interface IStatTableDisp : IDispatch
	{
		//params
		HRESULT getFirstParamPos( [out, retval]VARIANT* pv_pos );
		HRESULT getNextParamPos( [in]long lpos, [out, retval]VARIANT* pv_pos );
		HRESULT getParamKey( [in]long lpos, [out, retval]VARIANT* pv_key );		

		//rows
		HRESULT getFirstRowPos( [out, retval]VARIANT* pv_pos );
		HRESULT getNextRowPos( [in]long lpos, [out, retval]VARIANT* pv_pos );		
		HRESULT getRowCount( [out, retval]VARIANT* pv_count );
		
		HRESULT getRowGroup( [in]long lpos, [out, retval]VARIANT* pv_group );
		HRESULT getRowClass( [in]long lpos, [in]BSTR class_file, [out, retval]VARIANT* pv_class );
		HRESULT deleteRow( [in]long lpos );
		HRESULT getValueByKey( [in]long lpos, [in]long lkey, [out, retval]VARIANT* pv_value );
		HRESULT getValueByParamPos( [in]long lpos, [in]long lparam_pos, [out, retval]VARIANT* pv_value );

		HRESULT getGroupCount( [out, retval]VARIANT* pv_count );
		HRESULT getGroup( [in]long lpos, [out, retval]VARIANT* pv_group_ret );

		HRESULT updateObject( long lflags );
		HRESULT relloadSettings( long lflags );
		HRESULT GetPrivateNamedData( [out,retval] IDispatch **ppDisp );	

		[propget, helpstring("property Name")] HRESULT Name([out, retval] BSTR* pVal);
		[propput, helpstring("property Name")] HRESULT Name([in] BSTR newVal);

		HRESULT IsEmpty( [out, retval] VARIANT_BOOL *pvbIsEmpty );
		HRESULT GetType( [out, retval] BSTR *pbstrType );
		HRESULT getValueByKeyInUnit( [in]long lpos, [in]long lkey, [out, retval]VARIANT* pv_value );
		[id(1), helpstring("method UpdateClassNames")] HRESULT UpdateClassNames(void);
	};
}
