//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CCam.rc
//
#define IDS_PIXERA                      1
#define IDS_CCAM                        1
#define IDS_COLOR_BALANCE               2
#define IDS_IMAGE                       3
#define IDS_FRAME                       4
#define IDS_CAMERA                      5
#define IDS_NOLOGIC                     6
#define IDS_NOPCILOGIC                  7
#define IDS_LOGICNOLOAD                 8
#define IDS_7TO0                        9
#define IDS_8TO1                        10
#define IDS_9TO2                        11
#define IDS_10TO3                       12
#define IDS_11TO4                       13
#define IDS_9TO0                        14
#define IDS_11TO2                       15
#define IDS_11TO0                       16
#define IDS_FILE_NOT_OPENED             17
#define IDS_VIDEO_CAPTURED              18
#define IDD_PREVIEW                     102
#define IDD_SHUTTER                     106
#define IDD_LEVEL_ADJUSTMENT            107
#define IDD_COLOR_BALANCE               108
#define IDD_IMAGE                       110
#define IDC_SHUTTER_AUTO                1000
#define IDC_MOVE_SPOT                   1001
#define IDC_DLG_POS                     1002
#define IDC_COMBO_SPOT                  1003
#define IDC_CENTER_SPOT                 1004
#define IDD_DIALOG_SETTINGS             1004
#define IDC_COMBO_ADJUST                1006
#define IDC_AE_LOCK                     1008
#define IDD_PREVIEW_VIDEO               1008
#define IDC_STATIC_STATUS               1010
#define IDC_EDIT_EXP_TIME               1012
#define IDC_SPIN_EXP_TIME               1013
#define IDC_SLIDER_TIME                 1014
#define IDC_STATIC_GAIN                 1015
#define IDC_EDIT_GAIN                   1016
#define IDC_SPIN_GAIN                   1017
#define IDC_SLIDER_GAIN                 1018
#define IDC_EDIT_EXP_TIME2              1019
#define IDC_EDIT_LEVEL                  1019
#define IDC_COMBO_CHANNEL               1020
#define IDC_SPIN_EXP_TIME2              1020
#define IDC_SPIN_LEVEL                  1020
#define IDC_HISTO                       1021
#define IDC_SLIDER_TIME2                1021
#define IDC_SLIDER_LEVEL                1021
#define IDC_EDIT_SHADOW                 1022
#define IDC_EDIT_BRIGHTNESS             1022
#define IDC_EDIT_CONTRAST               1023
#define IDC_STATIC_PERIOD               1024
#define IDC_EDIT_HIGHLIGHT              1025
#define IDC_EDIT_GAMMA                  1025
#define IDC_STATIC_TIMEADJ              1026
#define IDC_SLIDER_SHADOW               1027
#define IDC_SLIDER_BRIGHTNESS           1027
#define IDC_COMBO_SENSITIVITY           1028
#define IDC_SLIDER_CONTRAST             1029
#define IDC_SLIDER_HIGHLIGHT            1030
#define IDC_SLIDER_GAMMA                1030
#define IDC_SPIN_SHADOW                 1031
#define IDC_SPIN_BRIGHTNESS             1031
#define IDC_SPIN_SHADOW2                1032
#define IDC_WB_OFF                      1033
#define IDC_FPS                         1033
#define IDC_WB_AUTO                     1034
#define IDC_TIME_LIM                    1034
#define IDC_WB_ONE_PUSH                 1035
#define IDC_WB_MANUAL                   1036
#define IDC_SPIN_CONTRAST               1037
#define IDC_SPIN_SHADOW3                1038
#define IDC_SPIN_HIGHLIGHT              1039
#define IDC_SPIN_GAMMA                  1039
#define IDC_SHOW_WB_RECT                1040
#define IDC_MOVE_WB_RECT                1041
#define IDC_CENTER_WB_RECT              1042
#define IDC_EDIT_WB_RED                 1043
#define IDC_SPIN_WB_RED                 1044
#define IDC_SLIDER_WB_RED               1045
#define IDC_EDIT_WB_GREEN               1046
#define IDC_CHECK_BB                    1047
#define IDC_SPIN_WB_GREEN               1048
#define IDC_SHOW_BB_RECT                1049
#define IDC_SLIDER_WB_GREEN             1050
#define IDC_MOVE_BB_RECT                1051
#define IDC_EDIT_WB_BLUE                1052
#define IDC_CENTER_BB_RECT              1053
#define IDC_SPIN_WB_BLUE                1054
#define IDC_EDIT_BB_GREEN               1055
#define IDC_SLIDER_WB_BLUE              1056
#define IDC_SPIN_BB_GREEN               1057
#define IDC_SLIDER_BB_GREEN             1058
#define IDC_EDIT_BB_BLUE                1059
#define IDC_SPIN_BB_BLUE                1060
#define IDC_SLIDER_BB_BLUE              1061
#define IDC_EDIT_BB_RED                 1062
#define IDC_SPIN_BB_RED                 1063
#define IDC_SLIDER_BB_RED               1064
#define IDC_CHECK_FLIP_VERT             1065
#define IDC_CHECK_FLIP_HORZ             1066
#define IDC_CHECK_GRAYSCALE             1067
#define IDC_COMBO_PREVIEW               1068
#define IDC_COMBO_CAPTURE               1069
#define IDC_EDIT_ACCUMULATION_TIMES     1070
#define IDC_SPIN_ACCUMULATION_TIMES     1071
#define IDC_COMBO_ACCUMULATION          1072
#define IDC_CHECK_FOCUS                 1073
#define IDC_STATIC_FOCUS                1074
#define IDC_STATIC_FOCUS_CURRENT        1074
#define IDC_MICRO_BRIGHT                1075
#define IDC_MICRO_FLUORESCENT           1076
#define IDC_WB_BUILD                    1077
#define IDC_SHOW_FOCUS_RECT             1078
#define IDC_MOVE_FOCUS_RECT             1079
#define IDC_CENTER_FOCUS_RECT           1080
#define IDC_STATIC_FOCUS_PEAK           1081
#define IDC_BB_BUILD                    1082
#define IDC_HISTOGRAM                   1083
#define IDC_SHOW_EXPOSURE_RECTANGLE     1084
#define IDC_DEFAULT                     1086
#define IDC_STATIC_ACCUMULATION         1087
#define IDC_DEFAULT2                    1087
#define IDC_EXACT_CONVERSION            1089
#define IDC_BITNESS                     1090
#define IDC_STATIC_BITS                 1091
#define IDC_BITS                        1092
#define IDC_EDIT_LEFT                   1093
#define IDC_SLIDER_LEFT                 1094
#define IDC_EDIT_RIGHT                  1095
#define IDC_EDIT_WIDTH                  1095
#define IDC_SLIDER_RIGHT                1096
#define IDC_SLIDER_WIDTH                1096
#define IDC_EDIT_TOP                    1097
#define IDC_SLIDER_TOP                  1098
#define IDC_EDIT_BOTTOM                 1099
#define IDC_EDIT_HEIGHT                 1099
#define IDC_SLIDER_BOTTOM               1100
#define IDC_SLIDER_HEIGHT               1100
#define IDC_USE_FRAME                   1101
#define IDC_SHOW_FRAME                  1102
#define IDC_CHECK_1_1                   1103
#define IDC_TAB_SELECT                  1103
#define IDC_EDIT_ZOOM                   1104
#define IDC_SPIN_ZOOM                   1105
#define IDC_SLIDER_ZOOM                 1106
#define IDC_CAMERA                      1107
#define IDC_COLOR_BALANCE               1108
#define IDC_LEVEL                       1109
#define IDC_EXACT                       1109
#define IDC_IMAGE_PAGE                  1110
#define IDC_BUTTON1                     1110
#define IDC_FRAME                       1111
#define IDC_SPIN_LEFT                   1111
#define IDC_IMAGE                       1112
#define IDC_SPIN_WIDTH                  1112
#define IDC_SPIN_TOP                    1113
#define IDC_SPIN4                       1114
#define IDC_SPIN_HEIGHT                 1114
#define IDC_VIDEO                       1114
#define IDC_TAB1                        1115
#define IDC_EDIT_SATURATION             1116
#define IDC_SPIN_SATURATION             1117
#define IDC_SLIDER_SATURATION           1118
#define IDC_COMBO_FORMATS               1119
#define IDC_SLIDER_OFFSET               1120
#define IDC_EDIT_OFFSET                 1121
#define IDC_SPIN_OFFSET                 1122
#define IDC_CAPTURE_FULL_FRAME          1123
#define IDC_EDIT_ODD_OFFSET             1124
#define IDC_SPIN_ODD_OFFSET             1125
#define IDC_SLIDER_ODD_OFFSET           1126
#define IDC_EDIT_TOTAL_SLOPES           1128
#define IDC_SPIN_TOTAL_SLOPES           1129
#define IDC_COMBO1                      1130
#define IDC_CURRENT_SLOPE               1130
#define IDC_CHECK1                      1131
#define IDC_CHECK_VERTICAL_MIRROR       1131
#define IDC_CHECK2                      1132
#define IDC_CHECK_HORIZONTAL_MIRROR     1132
#define IDC_CAPTURE_RATE_SCALE          1136
#define IDC_PLAYBACK_FPS                1137
#define IDC_PLAYBACK_RATE_SCALE         1138
#define IDC_TIME                        1139
#define IDC_FILE                        1140
#define IDC_PROGRESS_VIDEO_STAGE        1141
#define IDC_STATIC_VIDEO_STAGE          1142
#define IDC_CHECK_SAME_AS_CAPTURE       1143
#define IDC_BROWSE                      1289
#define IDD_HISTO                       2005
#define IDD_FRAME                       2006
#define IDD_CAMERA                      2007
#define IDD_PREVIEW1                    2008
#define IDD_SETTINGS                    2009
#define IDD_FRAME1                      2010
#define IDD_SETTINGS1                   2011
#define IDD_CAMERA_EX                   2011
#define IDD_PREVIEW2                    2012
#define IDD_VIDEO                       2013
#define IDD_VIDEO_EX                    2016
#define IDD_VIDEO_EX1                   2016
#define IDD_CAMERA_EX1                  2017
#define IDC_GRAY                        2068
#define IDC_RED                         2069
#define IDC_GREEN                       2070
#define IDC_BLUE                        2071
#define IDC_STATIC_MSG                  2076
#define IDC_STATIC_MAX_POINTS           2110
#define IDC_STATIC_MAX_COLOR            2111
#define IDC_STATIC_0                    2112
#define ID_SETTINGS                     57672
#define IDS_TIME_IN_SECONDS             61923
#define IDS_TIME_IN_MINUTES             61924
#define IDS_TIME_IN_HOURS               61925
#define IDS_INPUT                       61926
#define IDS_AE_STATE_UNDER              61927
#define IDS_AE_STATE_OVER               61928
#define IDS_AE_STATE_NORMAL             61929
#define IDS_AE_STATE_NOTFUNCTIONAL      61930
#define IDS_MS                          61931
#define IDS_MKS                         61932
#define IDS_TIME                        61933
#define IDS_ADJUST                      61934
#define IDS_SEC                         61935
#define IDS_NETWORK_PATH                61936

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1009
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           1086
#endif
#endif
