//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestUI.rc
//
#define ID_ACTION_EDITTESTDB            1
#define ID_ACTION_RUNTESTWINDOW         2
#define IDS_TEST_NAME                   3
#define IDS_TEST_DATE                   4
#define IDS_TEST_SAVING_DATE            4
#define IDS_TESTING_PANEL               5
#define IDS_TESTING_STATE               6
#define IDS_TESTING_DEVIATION           7
#define IDS_SELECTDIRFOREXPORT          8
#define IDS_NEW_TEST_NAME               9
#define IDS_STATICTICS                  10
#define IDS_STATISTICS                  10
#define IDS_ON_DELETE_TEST              11
#define IDS_ON_DELETE_GROUP             12
#define IDS_ON_RUN_TESTS_BRANCH         13
#define IDS_ON_START_RUN_TESTS_BRANCH   13
#define IDS_ON_END_RUN_TESTS_BRANCH     14
#define IDS_RECORD_STARTING             15
#define IDS_RUN_CURR_START_TEST         16
#define IDS_FILE_EXIST                  17
#define IDS_RUN_TEST_SEQUENCE_TITLE     18
#define IDS_RENAME_TEST_TITLE           19
#define IDS_ON_RENAME_TEST_ERROR        20
#define IDS_DELETE_TEST                 21
#define IDS_ON_END_RUN_FINAL_TESTS_BRANCH 22
#define IDS_VAR_NAME                    23
#define IDS_VAR_VALUE_SAMPLE            24
#define IDS_VAR_VALUE_CURR_TEST         25
#define IDS_TEST_LAST_RUN_DATE          26
#define IDS_COMMENTARY                  27
#define IDS_TEST_MODIFIED               28
#define IDS_ATTENTION                   29
#define IDS_COMB                        30
#define IDS_COMB_TEST                   31
#define IDS_COMB_TEST_REAL              32
#define IDS_COMB_TEST2                  32
#define IDS_ENV_INFO_STRING             33
#define IDS_NO_SAVED_ENV_STRING         34
#define IDS_NO_STRING                   34
#define IDD_TESTING_PROCESS             102
#define IDR_ALLRES                      1000
#define IDC_UNDO                        1000
#define IDC_REDO                        1001
#define IDC_TREE1                       1002
#define IDD_EDIT_TEST_DB                1002
#define IDC_EDIT_PERMANENT_START_CONDITIONS 1003
#define OBM_BUTTON_PERMANENT_START_CONDITIONS 1003
#define IDC_EDIT_START_CONDITIONS       1003
#define OBM_BUTTON_START_CONDITIONS     1003
#define IDC_EDIT_VARIANT_START_CONDITIONS 1004
#define IDC_EDIT_TEST_SEQUENCE          1005
#define IDB_TEST_SEQUENCE               1005
#define IDR_MENU_EDIT_TEST_DB           1005
#define IDC_BUTTON_PERMANENT_START_CONDITIONS 1006
#define ID_ADD_GROUP                    1006
#define IDC_BUTTON_START_CONDITIONS     1006
#define IDC_BUTTON_VARIANT_START_CONDITIONS 1007
#define ID_ADD_TEST                     1007
#define IDC_BUTTON_EXEC_COND            1007
#define IDC_BUTTON_TEST_SEQUENCE        1008
#define ID_DELETE                       1008
#define ID_COPY                         1009
#define IDC_LIST1                       1009
#define IDC_LIST_TESTS                  1009
#define IDC_LIST_TEST_PROCESS           1009
#define IDC_LIST_TESTS_RESULTS          1009
#define IDC_BUTTON_FINAL_TEST_SEQUENCE  1009
#define ID_PASTE                        1010
#define IDC_BUTTON_TEST_SYSTEM          1010
#define IDC_BUTTON_EDIT_TEST_SEQUENCE   1010
#define ID__ADDGROUP                    1011
#define IDC_BUTTON_SAVE_TEST            1011
#define IDC_BUTTON_EDIT_FINAL_TEST_SEQUENCE 1011
#define IDD_DIALOG1                     1012
#define IDD_RUN_TESTS                   1012
#define IDC_BUTTON_STOP                 1012
#define IDC_EDIT_FINAL_TEST_SEQUENCE    1012
#define IDC_BUTTON_VIEW_RESULTS         1013
#define IDC_COMBO_FILTRATION            1014
#define IDB_BITMAP_STOP                 1014
#define IDC_STATISTICS                  1014
#define IDR_HTML_COMPAREIMAGESDLG       1015
#define IDC_VIEW_HERE                   1015
#define IDC_BUTTON_PAUSE                1015
#define IDB_ADD_TEST                    1016
#define IDD_DIALOG_TESTING_RESULTS      1016
#define IDC_SCROLLBAR1                  1016
#define IDB_DELETE                      1017
#define IDD_DIALOG_TESTING_RESULTS1     1017
#define IDD_TESTING_PROCESS1            1017
#define IDC_SCROLLBAR2                  1017
#define IDR_MENU_TESTING_RESULTS        1018
#define IDC_VIEW_HERE2                  1018
#define ID_EXPORT_TEST                  1019
#define IDC_BUTTON1                     1019
#define IDB_COPY                        1020
#define ID_COMPARE_WITH_SAMPLE          1020
#define IDC_BUTTON2                     1020
#define IDB_BITMAP1                     1021
#define IDB_PASTE                       1021
#define ID_COMPARE_VALUES               1021
#define IDC_BUTTON3                     1021
#define IDB_EXPORT                      1022
#define IDC_BUTTON4                     1022
#define IDB_COMPARE_WITH_SAMPLE         1023
#define IDB_COMPARE_VALUES              1024
#define IDC_STATIC_RES                  1024
#define IDB_BITMAP_VIEW_RESULTS         1025
#define IDC_STATIC_MAIN                 1025
#define IDB_BITMAP_STOP1                1026
#define IDB_BITMAP_RUN                  1026
#define IDB_FOLDERS1                    1027
#define IDB_TESTS                       1027
#define IDC_COMBO_ARRAYS                1027
#define IDC_EDIT1                       1028
#define IDC_EDIT_INFO                   1028
#define IDC_EDIT_PATH                   1028
#define IDB_FOLDERS_RTD                 1030
#define IDB_FOLDERS_RUNTESTS            1030
#define IDC_EDIT_INFO2                  1030
#define IDC_COMBO1                      1030
#define IDC_COMBO_TYPES                 1030
#define IDD_COMPAREIMAGES               1031
#define ID__RENAME                      1032
#define IDC_EDIT_OBJ_NAME               1032
#define IDC_STATIC_CMB                  1033
#define IDB_RENAME                      1034
#define IDC_STATIC_STATE_INFO           1034
#define IDD_COMPARE_VALUES              1035
#define IDB_TEST_SEQUENCE1              1035
#define IDB_EDIT_TEST_SEQUENCE          1035
#define IDC_BUTTON_SAVE_STATE           1035
#define IDD_COMPAREIMAGES1              1036
#define IDD_INPUT_PATH                  1036
#define IDB_BITMAP_PAUSE                1036
#define IDC_BUTTON_SAVE_ENV             1036
#define IDC_STATIC_ENV_INFO             1037
#define IDC_CHECK_LOAD_SDC              1038
#define IDC_CHECK_LOAD_STATE            1039
#define IDC_EDIT_EXEC_COND              1040
#define IDC_STATIC_GR1                  1041
#define IDC_STATIC_T1                   1042
#define IDC_STATIC_T2                   1043
#define IDC_STATIC_T3                   1044
#define IDC_STATIC_T4                   1045
#define IDC_STATIC_GR2                  1046
#define IDC_STATIC_T5                   1047
#define IDC_STATIC_T6                   1048
#define IDC_CHECK1                      1049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1037
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           1016
#endif
#endif
