//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IV460Drv.rc
//
#define IDD_VIDEO_CAP                   120
#define IDC_PREVIEW                     1000
#define IDD_PREVIEW                     1000
#define IDC_FORMAT                      1002
#define IDC_SOURCE                      1003
#define IDD_SOURCE1                     1003
#define IDC_RED                         1004
#define IDC_GREEN                       1005
#define IDC_BLUE                        1006
#define IDC_SVIDEO                      1007
#define IDC_1STSVIDEO                   1008
#define IDC_2NDSVIDEO                   1009
#define IDC_ANALOG                      1010
#define IDC_2SVIDEO                     1011
#define IDC_VCR                         1012
#define IDC_AGC                         1013
#define IDC_E_BRIGHTNESS                1014
#define IDC_S_BRIGHTNESS                1015
#define IDC_E_CONTRAST                  1016
#define IDC_S_CONTRAST                  1017
#define IDC_E_HUE                       1018
#define IDC_S_HUE                       1019
#define IDC_E_SATURATION                1020
#define IDC_S_SATURATION                1021
#define IDC_DEFAULT                     1022
#define IDC_E_GWX                       1023
#define IDC_S_GWX                       1024
#define IDC_E_GWY                       1025
#define IDC_S_GWY                       1026
#define IDC_E_GWDX                      1027
#define IDC_S_GWDY                      1030
#define IDC_E_GWDY                      1031
#define IDC_S_GWDX                      1032
#define IDC_STANDARD_NTSC               1033
#define IDC_FPS                         1033
#define IDC_STANDARD_PAL                1034
#define IDC_TIME_LIM                    1034
#define IDC_STANDARD_SECAM              1035
#define IDC_STANDARD_NTSC44             1036
#define IDC_FILE                        1036
#define IDC_STANDARD_PALM               1037
#define IDC_STANDARD_PALN               1038
#define IDC_STANDARD                    1039
#define IDC_STANDARD_NTSCCOMB           1040
#define IDC_RADIO9                      1041
#define IDC_STANDARD_NTSCMONO           1042
#define IDC_STANDARD_SECAMMONO          1043
#define IDC_STANDARD_PAL60              1044
#define IDC_CAPTURE_VIDEO               1053
#define IDC_CAPTURE_MEMORY              1056
#define IDC_MESSAGE                     1058
#define IDC_PROGRESS_CONV               1059
#define IDC_FRAMES                      1060
#define IDC_GRAYSCALE                   1067
#define IDC_E_FRAME_SIZE                1078
#define IDC_S_FRAME_SIZE                1079
#define IDC_FPS_MESSAGE                 1081
#define IDC_STATIC_FRAME_SIZE           1082
#define IDC_STATIC_PROCENT              1083
#define IDC_CAPTURE_RATE_SCALE          1136
#define IDC_PLAYBACK_FPS                1137
#define IDC_PLAYBACK_RATE_SCALE         1138
#define IDC_TIME                        1139
#define IDC_BROWSE                      1289
#define IDC_SETTINGS                    2001
#define IDC_IMAGE                       2002
#define IDD_HISTO                       2005
#define IDC_E_WB_RED                    2023
#define IDC_S_WB_RED                    2024
#define IDC_E_WB_GREEN                  2025
#define IDC_S_WB_GREEN                  2026
#define IDC_E_WB_BLUE                   2027
#define IDC_S_WB_BLUE                   2028
#define IDC_WB_DEFAULT                  2029
#define IDC_WB_ENABLE                   2030
#define IDC_COMBO_CAMERA                2043
#define IDC_E_LEFT_MARGIN               2047
#define IDC_S_LEFT_MARGIN               2048
#define IDC_E_RIGHT_MARGIN              2049
#define IDC_S_RIGHT_MARGIN              2050
#define IDC_E_TOP_MARGIN                2051
#define IDC_S_TOP_MARGIN                2052
#define IDC_E_BOTTOM_MARGIN             2053
#define IDC_S_BOTTOM_MARGIN             2054
#define IDC_REFRESH_TIME                2055
#define IDD_WHITE_BALANCE               2060
#define IDD_FRAME                       2062
#define IDC_HISTO                       2067
#define IDC_GRAY                        2068
#define IDC_PREVIEW_ALL_FRAME           2072
#define IDC_STATIC_MSG                  2076
#define IDC_ENABLE_FRAME                2096
#define IDC_AVERAGE                     4000
#define IDC_RADIO_GAIN_OFFSET           4001
#define IDC_RADIO_TOP_BOTTOM            4002
#define IDC_GREEN_TOP_BOTTOM            4003
#define IDC_GREEN_CLAMP                 4004
#define IDC_RB_TOP_BOTTOM               4005
#define IDC_RB_CLAMP                    4006
#define IDC_GREEN_GAIN                  4007
#define IDD_SYNC_PAGE                   4007
#define IDC_EDIT_GREEN_TOP              4008
#define IDD_CAMERA_PAGE                 4008
#define IDC_SPIN_GREEN_TOP              4009
#define IDD_FORMAT_PAGE                 4009
#define IDC_STATIC_GREEN_TOP            4010
#define IDD_FRAME_PAGE                  4010
#define IDC_STATIC_GREEN_BOTTOM         4011
#define IDD_MAIN_PAGE                   4011
#define IDC_EDIT_GREEN_CLAMP            4012
#define IDD_PLL_PAGE                    4012
#define IDC_SPIN_GREEN_CLAMP            4013
#define IDD_CAMERA                      4013
#define IDC_EDIT_RB_BOTTOM              4014
#define IDD_SOURCE_RGB                  4014
#define IDC_SPIN_RB_BOTTOM              4015
#define IDC_EDIT_RB_TOP                 4016
#define IDC_SPIN_RB_TOP                 4017
#define IDC_EDIT_RB_CLAMP               4018
#define IDC_SPIN_RB_CLAMP               4019
#define IDC_EDIT_GREEN_BOTTOM           4020
#define IDC_SPIN_GREEN_BOTTOM           4021
#define IDC_GREEN_RANGE_TOP             4022
#define IDC_GREEN_RANGE_BOTTOM          4023
#define IDC_STATIC_GREEN_CLAMP          4024
#define IDC_GREEN_CLAMP_TOP             4025
#define IDC_GREEN_CLAMP_BOTTOM          4026
#define IDC_FRAME_GREEN                 4027
#define IDC_FRAME_RB                    4028
#define IDC_STATIC_RB_TOP               4029
#define IDC_STATIC_RB_BOTTOM            4030
#define IDC_STATIC_RB_CLAMP             4031
#define IDC_RB_RANGE_TOP                4032
#define IDC_RB_RANGE_BOTTOM             4033
#define IDC_RB_CLAMP_TOP                4034
#define IDC_RB_CLAMP_BOTTOM             4035
#define IDC_STATIC_GREEN_GAIN           4036
#define IDC_EDIT_GREEN_GAIN             4037
#define IDC_SPIN_GWX                    4037
#define IDC_SPIN_GREEN_GAIN             4038
#define IDC_SPIN_GWY                    4038
#define IDC_GREEN_GAIN_TOP              4039
#define IDC_SPIN_GWDX                   4039
#define IDC_GREEN_GAIN_BOTTOM           4040
#define IDC_SPIN_GWDY                   4040
#define IDC_FRAME_BLACKWHITE            4041
#define IDC_STANDARD_NONSTANDART        4041
#define IDC_PIXEL_RGB24                 4042
#define IDC_PIXEL_RGB32                 4043
#define IDC_STATIC_GREEN_OFFSET         4044
#define IDC_PIXEL_YUV16                 4044
#define IDC_EDIT_GREEN_OFFSET           4045
#define IDC_CAMERA_MONO8                4045
#define IDC_SPIN_GREEN_OFFSET           4046
#define IDC_CAMERA_RGB24                4046
#define IDC_GREEN_OFFSET_TOP            4047
#define IDC_CAMERA_YUV16                4047
#define IDC_GREEN_OFFSET                4048
#define IDC_CAMERA_MONO16               4048
#define IDC_GREEN_OFFSET_BOTTOM         4049
#define IDC_CAMERA_GRAYSCALE            4049
#define IDC_STATIC_RB_GAIN              4050
#define IDC_RADIO_GREEN                 4050
#define IDC_EDIT_RB_GAIN                4051
#define IDC_RADIO_RB                    4051
#define IDC_SPIN_RB_GAIN                4052
#define IDC_RB_GAIN_TOP                 4053
#define IDC_SLIDER_TOP_BOTTOM           4053
#define IDC_RB_GAIN                     4054
#define IDC_SLIDER_CLAMP                4054
#define IDC_RB_GAIN_BOTTOM              4055
#define IDC_RANGE_TOP                   4055
#define IDC_RANGE_BOTTOM                4056
#define IDC_GAIN_BOTTOM                 4057
#define IDC_GAIN_TOP                    4058
#define IDC_STATIC_RB_OFFSET            4059
#define IDC_EDIT_RB_OFFSET              4060
#define IDC_FRAME_BW                    4060
#define IDC_SPIN_RB_OFFSET              4061
#define IDC_STATIC_GAIN                 4061
#define IDC_STATIC_GAIN_R               4061
#define IDC_RB_OFFSET_TOP               4062
#define IDC_STATIC_OFFSET               4062
#define IDC_RB_OFFSET                   4063
#define IDC_STATIC_TOP                  4063
#define IDC_RB_OFFSET_BOTTOM            4064
#define IDC_STATIC_BOTTOM               4064
#define IDC_STATIC_CLAMP                4065
#define IDC_CLAMP_BOTTOM                4066
#define IDC_CLAMP_TOP                   4067
#define IDC_EDIT_TOP                    4068
#define IDC_SPIN_TOP                    4069
#define IDC_EDIT_BOTTOM                 4070
#define IDC_SPIN_BOTTOM                 4071
#define IDC_EDIT_CLAMP                  4072
#define IDC_SPIN_CLAMP                  4073
#define IDC_COLOR_CHANNEL               4074
#define IDC_INTERLACE                   4075
#define IDC_NONINTERLACE                4076
#define IDC_DETECTOR                    4077
#define IDC_INVERSE                     4078
#define IDC_EVEN                        4079
#define IDC_ODD                         4080
#define IDC_CLOCK_SYNC                  4081
#define IDC_CLOCK_EXT                   4082
#define IDC_NONINVERT                   4083
#define IDC_INVERT                      4084
#define IDC_PHASE                       4085
#define IDC_SPIN_PHASE                  4086
#define IDC_REF_NONINVERT               4089
#define IDC_REF_INVERT                  4090
#define IDC_LAG                         4091
#define IDC_LEAD                        4092
#define IDC_PERIOD                      4093
#define IDC_PIXEL_PER_LINE              4094
#define IDC_NEW                         4094
#define IDC_FREQ                        4095
#define IDC_CAMERA                      4095
#define IDC_BW_RS170                    4096
#define IDC_BW_CCIR                     4097
#define IDC_RGB_RS170                   4098
#define IDC_RGB_CCIR                    4099
#define IDC_USER_CAMERA                 4100
#define IDC_E_FILE_NAME                 4101
#define IDC_CHANNEL_RGB0                4103
#define IDC_CHANNEL_RGB1                4104
#define IDC_STATIC_GAIN_OFFSET          4105
#define IDC_STATIC_OFFSET_R             4106
#define IDC_E_GAIN_R                    4107
#define IDC_SP_GAIN_RED                 4108
#define IDC_S_GAIN_RED                  4109
#define IDC_E_OFFSET_R                  4110
#define IDC_SP_OFFSET_RED               4111
#define IDC_S_OFFSET_RED                4112
#define IDC_STATIC_GAIN_G               4113
#define IDC_E_GAIN_G                    4114
#define IDC_SP_GAIN_G                   4115
#define IDC_S_GAIN_GREEN                4116
#define IDC_STATIC_OFFSET_G             4117
#define IDC_E_OFFSET_G                  4118
#define IDC_SP_OFFSET_G                 4119
#define IDC_S_OFFSET_G                  4120
#define IDC_STATIC_GAIN_B               4122
#define IDC_E_GAIN_B                    4123
#define IDC_SP_GAIN_BLUE                4124
#define IDC_S_GAIN_BLUE                 4125
#define IDC_E_OFFSET_B                  4126
#define IDC_SP_OFFSET_BLUE              4127
#define IDC_S_OFFSET_BLUE               4128
#define IDC_STATIC_OFFSET_B             4129
#define IDS_INPUT                       61936

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4015
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4131
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
