//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DataView.rc
//
#define IDS_ERR_NODOCUMENT              100
#define IDS_ERR_CANTCREATEOBJECTLIST    101
#define IDS_ERR_NOIMAGE                 102
#define IDD_MEASUREMENT                 102
#define IDS_ERR_NOTINIMAGE              103
#define IDS_WRONG_PARAMETER             104
#define IDS_NO_CATIVE_DATAOBJECT        105
#define IDS_INVALIDOBJECT               106
#define IDS_INVALIDKEY                  107
#define IDS_NO_MANUAL_PARAMETER         108
#define IDS_INVALID_PARAM_TYPE          109
#define IDS_INVALID_PARAM_NAME          110
#define IDS_INVALID_NUIMERIC_VALUE      111
#define IDS_PARAM_NO                    112
#define IDS_PARAM_CLASS                 113
#define IDS_PARAM_VIEW                  114
#define IDS_EXT_CALIBRATION             115
#define IDC_CURSOR_WIDTH                132
#define IDC_CURSOR_COLUMN               133
#define IDC_CURSOR_HEIGHT               134
#define IDC_CURSOR_ROW                  135
#define IDC_CURSOR_COLUMN_SPLIT         136
#define IDC_CURSOR_ROW_SPLIT            137
#define IDR_ACRIONS                     3000
#define IDR_ACTIONS                     3000
#define IDC_RADIO_LINEAR                3000
#define IDC_COLOR                       3002
#define IDC_RADIO_ANGLE                 3002
#define IDC_RADIO_COUNT                 3003
#define IDD_DIALOG_PARAM                3003
#define IDC_RADIO_UNDEFINED             3004
#define IDC_SPIN_NUMBER                 3005
#define IDC_EDIT_NUMBER                 3006
#define IDC_EDIT_NAME                   3007
#define IDC_APPLY                       3008
#define IDC_COMBO                       3009
#define IDC_HORZ                        3010
#define IDC_VERT                        3011
#define IDC_CALIBR_NAME                 3012
#define IDC_CALIBR_UNIT                 3013
#define IDC_DIAGONAL                    3014
#define IDS_SHOW_CLASSVIEW              10000
#define IDS_ACTION_SHOW_CLASSVIEW       10000
#define IDS_ACTION_SHOW_MEASVIEW        10001
#define IDS_ACTION_CREATE_PARAM         10002
#define IDS_ACTION_REMOVE_PARAM         10003
#define IDS_ACTION_ZOOM_IN_TABLE        10004
#define IDS_ACTION_ZOOM_OUT_TABLE       10005
#define IDS_ACTION_REMOVE_MANUAL_MEAS   10009
#define IDS_ACTION_ALIGN_BY_CELL        10010
#define IDS_ACTION_ALIGN_BY_DEFAULT     10011
#define IDS_ACTION_SET_PARAM_VALUE      10012
#define IDS_ACTION_MOVE_PARAM           10013
#define IDS_ACTION_SET_PARAM_WIDTH      10014
#define IDS_ACTION_RENAME_PARAM         10015
#define IDS_ACTION_ALIGN_IMAGE          10016
#define IDS_ACTION_COPY_SELECTED        10017
#define IDS_ACTION_COPY_ALL             10018
#define IDS_ACTION_SET_OBJECT_HEIGHT    10019
#define IDS_MENU_VIEW                   20000
#define IDS_MENU_EDIT                   20001
#define IDS_TB_DATAVIEW                 20500
#define IDS_MEAS_VIEW                   20501
#define IDS_CLASS_VIEW                  20502
#define IDS_MEAS_SHIFT_PAGE             20503
#define IDR_DEFAULT_ACCEL               22901
#define ID_BUTTON32783                  32783
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3007
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         3016
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
