'resource:Method#Tools#Switch to Method mode#Switch to Method

Call MasterModeMethod_script

Sub	MasterModeMethod_script
	Dim objImageDoc
	ActionState.TerminateCurrentAction
	
	Set objImageDoc = Docs.GetActiveDocument("Image")
	If TypeName(objImageDoc) <> "Nothing" Then
		Docs.ActiveDocument = objImageDoc
	Else
		ActionManager.FileNew("Image")
		Set objImageDoc = Nothing
	End If
	MethodMan.Resume
End Sub