'resource:Rename Method#Method#Rename the selected method#Rename Method
'state:action=MtdCopyMethod

Call RenameMethod()
sub RenameMethod()
	Dim strNewName
	strNewName = Trim(InputBox(Docs.LoadString ("Enter new name for the selected method"), Docs.LoadString ("Rename Method")))
	If strNewName = "" Then
		Exit Sub
	Else
		MethodMan.RenameCurrentMethod strNewName
	MainWnd.UpdateSystemSettings
	End If
end sub