'resource:Edge Detection...#Enhance#Apply the Edge Detection filter to the image#Edge Detection
'state:action=Kirsch

Data.SetValue "\DockBars\VisibleTBName", Data.GetValue("\DockBars\TB_FiltersName")
If Data.GetValue("\DockBars\PageInProcessing") Then Data.SetValue "\DockBars\isPass", True

If isMaster Then
	FormManager.ExecutePageModal "EdgeDetection"
Else
	FormManager.ExecutePage "EdgeDetection"
End If