'resource:Fixed-Length Calibration Bar...#Measurement#Fixed-length calibration bar#Fixed-Length Calibration Bar
'state:action=Median

Dim s,m,c
set s = Objects.GetActiveObject( "Image" )
If TypeName(s.GetParent()) <> "Nothing" Then
	Set c = s.GetParent()
	Objects.SelectObject s, 0
	Objects.SelectObject c, 1
	m = 1
End If
FormManager.ExecuteModal "Marker"
If m Then SelectObjByName s.Name
set s = Nothing
Set c = Nothing