'resource:Morphological Filters...#Image#Morphological operations on source image#Morphological Filters
'state:action=Even

Data.SetValue "\General\EnableDock", 0
Data.SetValue "\DockBars\VisibleTBName", Data.GetValue("\DockBars\TB_FiltersName")

FormManager.ExecutePageModal "Morphology"

If MethodMan.IsRecording() = False or MethodMan.IsRunning() = False Then
	Data.SetValue "\General\EnableDock", 1
End If