'resource:Unsharp Mask...#Enhance#Increase the overall sharpness of the image#Unsharp Mask
'state:action=UnsharpenMask

Data.SetValue "\DockBars\VisibleTBName", Data.GetValue("\DockBars\TB_FiltersName")
If Data.GetValue("\DockBars\PageInProcessing") Then Data.SetValue "\DockBars\isPass", True

If isMaster Then
	FormManager.ExecutePageModal "Unsharpen"
Else
	FormManager.ExecutePage "Unsharpen" 
End If