'resource:All Elements to DB#Database#Send all elements to database by interaction settings#Send All Elements to DB
'state:function=StateImageNotEmpty

Data.RemoveValue "\tmpDB\"
Data.SetValue "\tmpDB\SendAllByOne", 1
Call send_to_db

'ѕравильное название при записи методики //
If Not Docs.IsPointerNull(MethodMan) Then
	If MethodMan.IsRecording() Then
		MethodMan.StoreStepAs Docs.LoadString ("Send All Elements to DB")
		MethodMan.CancelStepStoring
	End If
End If
