'resource:Manual Measurements#Tools#Show/hide Manual Measurements toolbar#Manual Measurements

ActionState.TerminateCurrentAction
BarNo = ToolBars.FindNo ( Docs.LoadString ("Manual Measurements"))
ToolBars.ShowBar BarNo , 1- ToolBars.IsBarVisible( BarNo )
If ToolBars.IsBarVisible( BarNo ) Then
	ActionState.SetActionState "ShowMeasManual", 1
Else
	ActionState.SetActionState "ShowMeasManual", 3
End If