'resource:Method List#Tools#Show/hide Method List toolbar#Method List
'state:function=IsMtdListToolBarVisible

ActionState.TerminateCurrentAction
BarNo = ToolBars.FindNo ( Docs.LoadString ("Method List"))
ToolBars.ShowBar BarNo , 1- ToolBars.IsBarVisible( BarNo )
If ToolBars.IsBarVisible( BarNo ) Then
	ActionState.SetActionState "ShowMtdListToolBar", 1
Else
	ActionState.SetActionState "ShowMtdListToolBar", 3
End If