'resource:Split and Synchronize#Window#Split document window vertically, show image and its Measurement Data#Split and Synchronize
'state:action=Median

Set img = Objects.ActiveImage
Set frame = MainWnd.ActiveFrame
Set s = frame.GetSplitter

s.Split 1, 1
'Objects.ActiveImage = img
s.Split 2, 1
s.SetViewType 1, 0, "DataView.MeasView"
s.ActivateView 0, 0, "ImageDoc.ImageView"
ActionManager.SyncContext 1
Set img = Nothing
Set frame = Nothing
Set s = Nothing