//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VTControls.rc
//
#define IDS_VTPUSHBUTTON                1
#define IDD_ABOUTBOX_VTPUSHBUTTON       1
#define IDB_VTPUSHBUTTON                1
#define IDI_ABOUTDLL                    1
#define IDS_VTKEYBUTTON                 1
#define IDD_ABOUTBOX_VTKEYBUTTON        1
#define IDB_VTCHECKBOX                  1
#define IDS_VTPUSHBUTTON_PPG            2
#define IDD_ABOUTBOX_VTSTATICTEXT       2
#define IDB_VTSTATICTEXT                2
#define IDS_VTKEYBUTTON_PPG             2
#define IDS_VTSTATICTEXT                3
#define IDD_ABOUTBOX_VTEDITOR           3
#define IDB_VTEDITOR                    3
#define IDS_VTSTATICTEXT_PPG            4
#define IDD_ABOUTBOX_VTLIST             4
#define IDB_VTLIST                      4
#define IDS_VTEDITOR                    5
#define IDD_ABOUTBOX_VTSLIDER           5
#define IDB_VTSLIDER                    5
#define IDS_VTEDITOR_PPG                6
#define IDB_PUSHBUTTON                  6
#define IDS_VTLIST                      7
#define IDS_VTLIST_PPG                  8
#define IDS_VTSLIDER                    9
#define IDS_VTSLIDER_PPG                10
#define IDS_VTLIST_PPGEX                11
#define IDS_VTLIST_PPGROW               12
#define IDS_VTEDITOR_PPG_EXT            13
#define IDS_PUSHBUTTON                  14
#define IDS_PUSHBUTTON_PPG              15
#define IDS_PUSHBUTTON_FAMESPPG         16
#define IDS_VTSTATICTEXT_PPG_EXT        17
#define IDS_VTKEYIMAGEBUTTON_PPG        18
#define IDS_VTCHECKBOX                  19
#define IDS_VTCHECKBOX_PPG              20
#define IDS_VTLIST_PPGHEADER            21
#define IDD_PROPPAGE_VTKEY_IMAGE        104
#define IDS_VTPUSHBUTTON_PPG_CAPTION    200
#define IDD_PROPPAGE_VTPUSHBUTTON       200
#define IDS_VTKEYBUTTON_PPG_CAPTION     200
#define IDD_PROPPAGE_VTKEYBUTTON        200
#define IDS_VTSTATICTEXT_PPG_CAPTION    201
#define IDD_PROPPAGE_VTSTATICTEXT       201
#define IDC_USEGRID                     201
#define IDC_EDIT_FILENAME               201
#define IDB_CHECKED                     201
#define IDC_CAPTION                     201
#define IDS_VTEDITOR_PPG_CAPTION        202
#define IDD_PROPPAGE_VTEDITOR           202
#define IDI_TRUE                        202
#define IDC_USE_FULL_ROW_SELECT         202
#define IDC_BUTTON_FILEOPEN             202
#define IDS_VTLIST_PPG_CAPTION          203
#define IDD_PROPPAGE_VTLIST             203
#define IDI_FALSE                       203
#define IDC_LIST                        203
#define IDC_EDIT_WIDTH                  203
#define IDC_VTCHECKBOXCTRL1             203
#define IDS_VTSLIDER_PPG_CAPTION        204
#define IDD_PROPPAGE_VTSLIDER           204
#define IDC_BUTTON_ADD                  204
#define IDC_EDIT_HEIGHT                 204
#define IDI_DOWN                        204
#define IDD_PROPPAGE_VTLISTEX           205
#define IDS_VTLIST_PPGEX_CAPTION        205
#define IDC_BUTTON_DELETE               205
#define IDC_CHECK_AUTOSIZE              205
#define IDI_LEFT                        205
#define IDC_COMBO_COLUMN_TYPE           206
#define IDD_PROPPAGE_VTLIST_ROW         206
#define IDS_VTLIST_PPGROW_CAPTION       206
#define IDC_BUTTON_RELOAD               206
#define IDI_RIGHT                       206
#define IDC_BUTTON_FORE_COLOR           207
#define IDD_DIALOG1                     207
#define IDS_VTEDITOR_PPG_EXT_CAPTION    207
#define IDI_SHIFT                       207
#define IDC_BUTTON_BACK_COLOR           208
#define IDD_PROPPAGE_VTEDITOR_EXT       208
#define IDS_PUSHBUTTON_PPG_CAPTION      208
#define IDC_COMBO_ALIGN                 209
#define IDS_PUSHBUTTON_FAMESPPG_CAPTION 209
#define IDC_BUTTON_FONT                 210
#define IDC_SPIN_SHADOW                 210
#define IDS_VTSTATICTEXT_PPG_EXT_CAPTION 210
#define IDC_TEST_STRING                 211
#define IDC_EDIT_BUTTONDEPTH            211
#define IDS_WAITING                     211
#define IDI_ICON_RELOAD                 212
#define IDS_KEY_MESSAGE                 212
#define IDC_CHECK_LOG_AS_TEXT           213
#define IDS_KEY_PICK_PROCESS            213
#define IDS_VTKEYIMAGEBUTTON_PPG_CAPTION 214
#define IDC_CHECK_USE_ICON              215
#define IDS_VTCHECKBOX_PPG_CAPTION      215
#define IDC_ROW_LIST                    216
#define IDS_VTLIST_PPGHEADER_CAPTION    216
#define IDC_BUTTON_ADD_ROW              217
#define IDC_BUTTON_SET_ICON             219
#define IDC_ICON_VIEW                   220
#define IDI_BROWSE                      220
#define IDC_BUTTON_DELETE_ROW           221
#define IDI_UP                          221
#define IDC_VTLIST1                     226
#define IDC_BUTTON_CLEAR_ICON           227
#define IDC_BUTTON_SET_TRUE_ICON        228
#define IDC_BUTTON_SET_FALSE_ICON       229
#define IDC_STATIC_CUR_COLUMN           230
#define IDC_CHECK1                      230
#define IDC_BUTTON_SET_GRAY_ICON        230
#define IDC_BUTTON_CUR_COLUMN_LEFT      231
#define IDC_CHECK2                      231
#define IDC_BUTTON_CUR_COLUMN_RIGHT     232
#define IDC_CHECK_READ_ONLY             233
#define IDC_CHECK4                      233
#define IDC_EDIT_COL_WIDTH              234
#define IDC_CHECK5                      234
#define IDC_LIST_ROW                    236
#define IDC_BUTTON_REFRESH              237
#define IDC_CHECK_MOUSEIN_COLOR         237
#define IDC_EDIT_KEY_VALUE              238
#define IDC_CHECK_MOUSEIN_SHADOW        238
#define IDC_BUTTON_SET_KEY              239
#define IDC_CHECK_MOUSEOUT_COLOR        239
#define IDC_CHECK_AUTO_SAVE_TO_SHELL    240
#define IDC_CHECK_MOUSEOUT_SHADOW       240
#define IDC_CHECK_BPRESSED_COLOR        241
#define IDC_SIMPLE_FONT_CHOOSER         241
#define IDC_CHECK_BPRESSED_SHADOW       242
#define IDC_CHECK_ENABLE                243
#define IDC_EDIT_NAME                   244
#define IDC_CHECK_FLATBUTTON            245
#define IDC_SPIN_WIDTH                  246
#define IDC_CHECK_DRAWBORDER            246
#define IDC_CHECKTREESTATE              247
#define IDB_VTKEYBUTTON                 247
#define IDC_COMBO_CAPTION_ALIGN         250
#define IDC_EDIT_CAPTION_TEXT           251
#define IDC_EDIT_MIN_VALUE              252
#define IDB_BITMAP1                     252
#define IDC_EDIT_MAX_VALUE              253
#define IDC_COMBO_DATA_TYPE             254
#define IDI_SHADING1                    254
#define IDC_SPIN_MIN                    255
#define IDI_SHADING2                    255
#define IDC_SPIN_MAX                    256
#define IDI_SHADING3                    256
#define IDC_CHECK_ENABLE_VALIDATION     257
#define IDI_SHADING4                    257
#define IDC_CHECK_CAPTION_ENABLE        258
#define IDI_SHADING5                    258
#define IDC_CHECK_ENABLE_SPIN           259
#define IDI_SHADING6                    259
#define IDC_EDIT_FIELD_WIDTH            260
#define IDI_SHADING7                    260
#define IDC_SPIN_EDIT_WIDTH             261
#define IDI_SHADING8                    261
#define IDC_CHECK_ENABLE_CAPTION_AUTO_WIDTH 262
#define IDI_SHADING9                    262
#define IDC_CHECK_AUTO_UPDATE           263
#define IDI_SHADING10                   263
#define IDI_SHADING11                   264
#define IDI_SHADING12                   265
#define IDC_CHECK_MULTI_LINE            266
#define IDI_SHADING13                   266
#define IDC_CHECK_ALIGN_CLIENT          267
#define IDC_EDIT1                       268
#define IDC_VIRT_KEY                    268
#define IDC_ITEM_WIDTH                  268
#define IDC_TOOLTIP                     268
#define IDC_EDIT_TOOLTIP                268
#define IDI_SHADING14                   267
#define IDC_SPIN1                       269
#define IDC_ITEM_DELTA_X                269
#define IDI_SHADING15                   268
#define IDC_EDIT2222                    270
#define IDC_ITEM_HEIGHT                 270
#define IDI_SHADING16                   269
#define IDI_ICON1                       270
#define IDC_BUTTON_AUTO_SIZE            271
#define IDC_SPIN2                       271
#define IDC_ITEM_DELTA_Y                271
#define IDC_CHECK_TOP_TEXT              272
#define IDC_IMAGE_INDEX                 272
#define IDC_CHECK_LEFT_TEXT             273
#define IDC_SPIN3                       273
#define IDC_CHECK_RIGHT_TEXT            274
#define IDC_CHECK_BOTTOM_TEXT           275
#define IDC_CHECK_FOCUSRECT             276
#define IDC_CHECK_LEFT_PIC              276
#define IDC_CHECK_STRETCH               277
#define IDC_CHECK_RIGHT_PIC             277
#define IDC_CHECK_TOP_PIC               278
#define IDC_CHECK_BOTTOM_PIC            279
#define IDC_CHECK_LEFT_TEXT_TO_PIC      280
#define IDC_CHECK_RIGHT_TEXT_TO_PIC     281
#define IDC_CHECK_TOP_TEXT_TO_PIC       282
#define IDC_CHECK_BOTTOM_TEXT_TO_PIC    283
#define IDC_EDIT_TEXT                   284
#define IDC_EDIT_PIC_FILENAME           285
#define IDC_CHECK_CENTER_IMAGE          286
#define IDC_EDIT_LOW_KEY                287
#define IDC_EDIT_HIGH_KEY               288
#define IDC_CHECK_CENTER_TEXT           288
#define IDC_EDIT_MIN                    289
#define IDC_CHECK_MIDDLE_TEXT           289
#define IDC_EDIT_MAX                    290
#define IDC_CHECK_SHOW_NUM              291
#define IDC_CHECK_TICK                  292
#define IDC_CHECK_CYCLED                293
#define IDC_EDIT_TICK_FREQ              294
#define IDC_EDIT_ACTION_NAME            295
#define IDC_CHECK_IS_RUN_ACTION         296
#define IDD_PROPPAGE_FRAMES             301
#define IDC_PUSHBUTTONCTRL1             301
#define IDD_PROPPAGE_PUSHBUTTON         302
#define IDC_CHECKSINGLE_SLIDE           302
#define IDD_PROPPAGE_VTSTATICTEXT_EXT   303
#define IDC_CHECK_TRANSPARENCY          303
#define IDC_COMBO_TEMPLATE              304
#define IDD_PROPPAGE_VTCHECKBOX         304
#define IDD_ABOUTBOX_VTCHECKBOX         305
#define IDD_PROPPAGE_VTLIST_HEADER      306
#define IDC_AUTO_REPEAT                 330
#define IDC_VTKEYBUTTON1                331
#define IDC_BTN_PICK                    332
#define IDC_STATE                       333
#define IDC_ALIGN_HORZ                  335
#define IDC_ALIGN_VERT                  336
#define IDC_NEW_DRAWING_MODE            336
#define IDC_DRAW_FOCUSED_RECT           337
#define IDC_VTEDITOR1                   338
#define IDC_3DAPPEARANCE                340
#define IDC_SEMIFLAT                    341
#define IDC_PASTE                       342
#define IDC_COPY                        343
#define IDC_USE_SYSTEM_FONT             343
#define IDC_SYSTEM_FONT                 344
#define IDC_SHOWTOOLTIP                 345
#define IDC_RESIZE_COLS                 346
#define IDC_EDIT2                       353
#define IDC_SPIN4                       354
#define IDC_EDIT3                       355
#define IDC_SPIN5                       356
#define IDC_EDIT4                       357
#define IDC_SPIN6                       358
#define IDC_STATIC_LEV                  359
#define IDC_STATIC_CLEV                 360
#define IDC_STATIC_CNT                  361
#define IDC_STATIC_NLEV                 362
#define IDC_BUTTON_DELETE_HEADER        364
#define IDC_BUTTON_ADD_HEADER           365
#define IDC_STATIC_WIDTH                366

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        271
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         367
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
