//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Pixera.rc
//
#define IDS_PIXERA                      1
#define IDD_PREVIEW                     102
#define IDD_SHUTTER                     106
#define IDD_LEVEL_ADJUSTMENT            107
#define IDD_COLOR_BALANCE               108
#define IDD_BLACK_BALANCE               109
#define IDD_IMAGE                       110
#define IDC_SHUTTER_AUTO                1000
#define IDC_MOVE_SPOT                   1001
#define IDC_DLG_POS                     1002
#define IDD_WAIT                        1002
#define IDC_COMBO_SPOT                  1003
#define IDC_CENTER_SPOT                 1004
#define IDD_DIALOG1                     1004
#define IDC_IMAGE                       1005
#define IDD_DIALOG_SETTING_NAME         1005
#define IDD_DIALOG_SETTING_NAME11       1005
#define IDC_COMBO_ADJUST                1006
#define IDC_LEVEL                       1007
#define IDC_AE_LOCK                     1008
#define IDC_COLOR_BALANCE               1009
#define IDC_STATIC_STATUS               1010
#define IDC_IMAGE_PAGE                  1011
#define IDC_EDIT_EXP_TIME               1012
#define IDC_SPIN_EXP_TIME               1013
#define IDC_SLIDER_TIME                 1014
#define IDC_STATIC_SENSITIVITY          1015
#define IDC_EDIT_SENSITIVITY            1016
#define IDC_SPIN_SENSITIVITY            1017
#define IDC_SLIDER_SENSITIVITY          1018
#define IDC_BLACK_BALANCE               1019
#define IDC_COMBO_CHANNEL               1020
#define IDC_HISTO                       1021
#define IDC_EDIT_SHADOW                 1022
#define IDC_EDIT_GAMMA                  1023
#define IDC_STATIC_PERIOD               1024
#define IDC_EDIT_HIGHLIGHT              1025
#define IDC_STATIC_TIMEADJ              1026
#define IDC_SLIDER_SHADOW               1027
#define IDC_COMBO_SENSITIVITY           1028
#define IDC_SLIDER_GAMMA                1029
#define IDC_SLIDER_HIGHLIGHT            1030
#define IDC_SPIN_SHADOW                 1031
#define IDC_SPIN_SHADOW2                1032
#define IDC_WB_OFF                      1033
#define IDC_WB_AUTO                     1034
#define IDC_WB_ONE_PUSH                 1035
#define IDC_WB_MANUAL                   1036
#define IDC_SPIN_GAMMA                  1037
#define IDC_SPIN_SHADOW3                1038
#define IDC_SPIN_HIGHLIGHT              1039
#define IDC_SHOW_WB_RECT                1040
#define IDC_MOVE_WB_RECT                1041
#define IDC_CENTER_WB_RECT              1042
#define IDC_EDIT_WB_RED                 1043
#define IDC_SPIN_WB_RED                 1044
#define IDC_SLIDER_WB_RED               1045
#define IDC_EDIT_WB_GREEN               1046
#define IDC_CHECK_BB                    1047
#define IDC_SPIN_WB_GREEN               1048
#define IDC_SHOW_BB_RECT                1049
#define IDC_SLIDER_WB_GREEN             1050
#define IDC_MOVE_BB_RECT                1051
#define IDC_EDIT_WB_BLUE                1052
#define IDC_CENTER_BB_RECT              1053
#define IDC_SPIN_WB_BLUE                1054
#define IDC_EDIT_BB_GREEN               1055
#define IDC_SLIDER_WB_BLUE              1056
#define IDC_SPIN_BB_GREEN               1057
#define IDC_SLIDER_BB_GREEN             1058
#define IDC_EDIT_BB_BLUE                1059
#define IDC_SPIN_BB_BLUE                1060
#define IDC_SLIDER_BB_BLUE              1061
#define IDC_EDIT_BB_RED                 1062
#define IDC_SPIN_BB_RED                 1063
#define IDC_SLIDER_BB_RED               1064
#define IDC_CHECK_FLIP_VERT             1065
#define IDC_CHECK_FLIP_HORZ             1066
#define IDC_CHECK_GRAYSCALE             1067
#define IDC_COMBO_PREVIEW               1068
#define IDC_COMBO_CAPTURE               1069
#define IDC_EDIT_ACCUMULATION_TIMES     1070
#define IDC_SPIN_ACCUMULATION_TIMES     1071
#define IDC_COMBO_ACCUMULATION          1072
#define IDC_CHECK_FOCUS                 1073
#define IDC_STATIC_FOCUS                1074
#define IDC_STATIC_FOCUS_CURRENT        1074
#define IDC_MICRO_BRIGHT                1075
#define IDC_MICRO_FLUORESCENT           1076
#define IDC_WB_BUILD                    1077
#define IDC_SHOW_FOCUS_RECT             1078
#define IDC_MOVE_FOCUS_RECT             1079
#define IDC_CENTER_FOCUS_RECT           1080
#define IDC_STATIC_FOCUS_PEAK           1081
#define IDC_BB_BUILD                    1082
#define IDC_HISTOGRAM                   1083
#define IDC_SHOW_EXPOSURE_RECTANGLE     1084
#define IDC_DEFAULT                     1086
#define IDC_STATIC_ACCUMULATION         1087
#define IDC_STATIC_PERIOD1              1088
#define IDC_LIST1                       1090
#define IDC_BUTTON_NEW_SETTINGS         1091
#define IDC_BUTTON_DELETE_SETTINGS      1092
#define IDC_BUTTON_SAVE_SETTINGS        1093
#define IDC_EDIT1                       1094
#define IDC_EDIT2                       1095
#define IDC_LIST11                      1096
#define IDC_BUTTON_NEW_SETTINGS11       1097
#define IDC_BUTTON_DELETE_SETTINGS11    1098
#define IDC_BUTTON1                     1099
#define IDD_SETTING                     1100
#define IDC_EDIT11                      1100
#define IDC_SETTING1                    1101
#define IDC_SETTING11                   1102
#define IDD_SETTING11                   1103
#define IDCANCEL11                      1104
#define IDD_HISTO                       2005
#define IDD_DIALOG_SETTING_NAME12       2006
#define IDD_DIALOG_SETTING_NAME13       2007
#define IDC_GRAY                        2068
#define IDC_RED                         2069
#define IDC_GREEN                       2070
#define IDC_BLUE                        2071
#define IDC_STATIC_MSG                  2076
#define IDC_STATIC_MAX_POINTS           2110
#define IDC_STATIC_MAX_COLOR            2111
#define IDC_STATIC_0                    2112
#define IDS_INPUT                       61926
#define IDS_AE_STATE_UNDER              61927
#define IDS_AE_STATE_OVER               61928
#define IDS_AE_STATE_NORMAL             61929
#define IDS_AE_STATE_NOTFUNCTIONAL      61930
#define IDS_MS                          61931
#define IDS_MKS                         61932
#define IDS_TIME                        61933
#define IDS_ADJUST                      61934
#define IDS_SEC                         61935
#define IDS_NEW_METHODIC                61936

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1006
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
