//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vtcontrols2.rc
//
#define IDS_VTCOMBOBOX                  1
#define IDB_VTCOMBOBOX                  1
#define IDS_VTCOMBOBOX_PPG              2
#define IDB_VTCOLORPICKER               2
#define IDS_VTCOLORPICKER               3
#define IDB_VTWIDTH                     3
#define IDS_VTCOLORPICKER_PPG           4
#define IDB_VTCOMBOBOX2                 4
#define IDS_VTWIDTH                     5
#define IDS_VTWIDTH_PPG                 6
#define IDS_VTCOMBOBOX2                 7
#define IDS_COLORRANGE                  8
#define IDS_COLORRANGE_PPG              9
#define IDS_WRONG_WIDTH                 10
#define IDS_VTRADIOBTN                  11
#define IDS_VTRADIOBTN_PPG              12
#define IDS_VTPROGRESSBAR               13
#define IDS_VTPROGRESSBAR_PPG           14
#define IDS_VTRADIOBTN_PPG_TWO_CAPTION  15
#define IDC_BUTTONWIDTH                 101
#define IDC_BUTTONUP                    102
#define IDC_BUTTONDOWN                  103
#define IDC_BUTTONSLIDER                104
#define IDD_PROPPAGE_VTRADIOBTN_TWO     104
#define IDD_BCGBARRES_COLOR_PAGE_ONE    105
#define IDD_BCGBARRES_COLORPAGE_TWO     106
#define IDC_BCGBARRES_HEXPLACEHOLDER    107
#define IDC_BCGBARRES_GREYSCALEPLACEHOLDER 108
#define IDC_COLORBUTTON                 109
#define IDD_COLORBTNDLG_DIALOG          110
#define IDS_VTCOMBOBOX_PPG_CAPTION      200
#define IDD_PROPPAGE_VTCOMBOBOX         200
#define IDS_VTCOLORPICKER_PPG_CAPTION   201
#define IDD_PROPPAGE_VTCOLORPICKER      201
#define IDC_EDIT_MIN                    201
#define IDS_VTWIDTH_PPG_CAPTION         202
#define IDD_PROPPAGE_VTWIDTH            202
#define IDC_EDIT_MAX                    202
#define IDC_SPIN1                       203
#define IDD_DIALOGWIDTH                 203
#define IDS_FIRST_TYPE                  203
#define IDC_EDIT_POS                    203
#define IDS_SECOND_TYPE                 204
#define IDC_BUTTON1                     204
#define IDS_COLORRANGE_PPG_CAPTION      205
#define IDC_BUTTON2                     205
#define IDC_LIST2                       206
#define IDS_VTRADIOBTN_PPG_CAPTION      206
#define IDC_BUTTON3                     207
#define IDS_VTPROGRESSBAR_PPG_CAPTION   207
#define IDC_BUTTON4                     208
#define IDC_EDIT1                       209
#define IDC_BUTTON5                     210
#define IDD_DIALOG1                     234
#define IDC_EDITMIN                     244
#define IDC_EDITWIDTH                   246
#define IDC_EDITMAX                     247
#define IDC_CHECKORIENTATION            250
#define IDC_CHECKCHECKED                251
#define IDD_BCGBARRES_COLOR_DLG         340
#define IDD_COLOR_DLG                   341
#define IDD_DIALOG2                     342
#define IDD_BCGBARRES_COLOR_PAGE_THREE  342
#define IDD_PROPPAGE_COLORRANGE         343
#define IDD_PROPPAGE_VTRADIOBTN         344
#define IDD_PROPPAGE_VTPROGRESSBAR      345
#define IDC_BCGBARRES_STATICPLACEHOLDER 364
#define IDC_BCGBARRES_COLOURPLACEHOLDER 365
#define IDC_BCGBARRES_SPIN1             371
#define IDC_BCGBARRES_R                 372
#define IDC_BCGBARRES_B                 373
#define IDC_BCGBARRES_SPIN2             374
#define IDC_BCGBARRES_G                 375
#define IDC_BCGBARRES_SPIN3             376
#define IDC_BCGBARRES_L                 377
#define IDC_BCGBARRES_SPIN4             378
#define IDC_BCGBARRES_H                 379
#define IDD_DIALOG3                     379
#define IDC_BCGBARRES_SPIN5             380
#define IDC_BCGBARRES_S                 381
#define IDC_BCGBARRES_SPIN6             382
#define IDC_BCGBARRES_LUMINANCEPLACEHOLDER 388
#define IDC_COLOR1                      389
#define IDC_COLOR2                      390
#define IDC_COLOR3                      391
#define IDC_COLOR4                      392
#define IDC_COLOR5                      393
#define IDC_COLOR6                      394
#define IDC_COLOR7                      395
#define IDC_COLOR8                      396
#define IDC_COLOR9                      397
#define IDC_COLOR10                     398
#define IDC_COLOR11                     399
#define IDC_COLOR12                     400
#define IDC_COLOR13                     401
#define IDC_COLOR14                     402
#define IDC_COLOR15                     403
#define IDC_COLOR16                     404
#define IDD_DIALOG4                     404
#define IDC_COLOR17                     405
#define IDC_COLOR18                     406
#define IDC_COLOR19                     407
#define IDC_COLOR20                     408
#define IDC_COLOR21                     409
#define IDC_COLOR22                     410
#define IDC_COLOR23                     411
#define IDR_ACCELERATOR1                411
#define IDC_COLOR24                     412
#define IDC_COLOR25                     413
#define IDC_COLOR26                     414
#define IDC_COLOR27                     415
#define IDC_COLOR28                     416
#define IDC_COLOR29                     417
#define IDC_COLOR30                     418
#define IDC_OTHER                       419
#define IDC_LISTDROPDOWN                426
#define IDC_EDITSTRING                  427
#define IDC_BUTTONINSERT                428
#define IDC_BUTTONDELETE                429
#define IDC_BUTTONDELETEALL             430
#define IDD_DIALOG5                     437
#define IDD_DIALOG6                     442
#define IDB_COLORRANGE                  456
#define IDI_SLIDER                      457
#define IDI_COLOR_SLIDER                457
#define IDB_VTRADIOBTN                  462
#define IDB_VTPROGRESSBAR               463
#define IDC_CHECK1                      466
#define IDC_EDITSIZEHEIGHT              493
#define IDC_EDITSIZEWIDTH               494
#define IDC_CHECKBAW                    526
#define IDC_BCGBARRES_GREYHEXPLACEHOLDER 537
#define IDC_BCGBARRES_GREYLUMPLACEHOLDER 538
#define IDC_EDIT_LUMINANCE              539
#define IDC_BAW_SPIN1                   540
#define IDC_BAW_G                       541
#define IDC_BAW_B                       542
#define IDC_BAW_R                       543
#define IDC_SPIN2                       544
#define IDC_BAW_SPIN3                   544
#define IDC_SPIN3                       545
#define IDC_BAW_SPIN4                   545
#define IDC_BAW_SPIN2                   546
#define IDC_CHECK2                      550
#define IDC_COMBO_TYPE                  552
#define IDC_ENABLE                      553
#define IDC_VISIBLE                     554
#define IDC_SMOOTH                      555
#define IDC_SHOW_PERCENT                556
#define IDC_EVENLYSPACED                557
#define IDC_DROPDOWN                    32768

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        464
#define _APS_NEXT_COMMAND_VALUE         32769
#define _APS_NEXT_CONTROL_VALUE         558
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
